// The command surface, in the one file `build.rs` also reads.
//
// Nothing but `clap` is used here, and nothing from the rest of the crate,
// because `build.rs` `include!`s this file in order to generate the man page
// from it. That is what makes `kbsetup.8` impossible to leave stale: there is no
// committed copy to forget, and the page is the source of truth's own account
// of itself.
//
// Plain comments rather than `//!` for the same reason: an inner doc comment is
// only legal at the top of the file it ends up in, and this one ends up in the
// middle of `build.rs`.

use std::path::PathBuf;

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(
    name = "kbsetup",
    version,
    about = "Bring a KerBridge realm and its directory into existence, and check they still match",
    long_about = "KerBridge's setup CLI. `kbsetup` brings a deployment into existence,\n\
                  `kbconfig` owns its configuration, and `kbmanage` runs it day to day --\n\
                  setup, config, manage.\n\n\
                  Every verb is idempotent and reads the config set in process. `realm` and\n\
                  `directory` are operator-invoked, once each per deployment plus once more\n\
                  per cloud IdP added; `verify` runs on the issuer daemon's start path and\n\
                  must stay cheap and read-only.\n\n\
                  This runs as root on the domain controller itself. It creates nothing an\n\
                  operator did not ask for: no package installs a realm, and nothing here\n\
                  reconfigures a subsystem that is not KerBridge's."
)]
pub struct Cli {
    /// The config set's directory; every file in it is read
    #[arg(long, global = true, value_name = "PATH")]
    pub config: Option<PathBuf>,
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Subcommand)]
pub enum Command {
    /// Provision the realm if there is none, or verify and refuse if there is.
    ///
    /// Creates the LDAPS CA and the SAN certificate Samba's own autogenerated
    /// one cannot replace, generates the Administrator password if the file the
    /// config set names is absent or empty, runs the provisioner, and writes the
    /// Kerberos drop-in that names this KDC explicitly.
    ///
    /// Everything it decides is baked into the Samba database and cannot be
    /// changed afterwards by editing configuration.
    Realm {
        /// Provision the documented example realm on purpose.
        ///
        /// Without this, a config set still naming EXAMPLE.SITE is refused while
        /// there is nothing to lose. The values are unchangeable once
        /// provisioned: correcting one later destroys the domain SID and every
        /// filesystem ACL carrying it.
        #[arg(long)]
        allow_example_realm: bool,
    },
    /// Create the OUs, the service accounts, their delegation and the deny.
    ///
    /// Seeds no users and no groups -- a kerbridge-sync owns each source OU's
    /// content. Re-run it after adding a cloud IdP to the config set; it creates
    /// only what is absent.
    Directory,
    /// Does durable state still match the config set.
    ///
    /// Compares the three values provisioning baked in and the five a component
    /// depends on, republishes the realm CA if it has gone missing, and checks
    /// the Kerberos drop-in.
    ///
    /// Exits 0 when it matches -- warnings ride on 0 -- 2 when it does not, and
    /// 1 on an error. A mismatch here stops the bridge, never the domain
    /// controller.
    Verify,
}
