//! The Kerberos client configuration a DC needs in order to be its own client.
//!
//! **A drop-in, not the file.** `/etc/krb5.conf` belongs to
//! `kerbridge-issuerd`'s maintainer script, which owns one greppable line --
//! `includedir /etc/krb5.conf.d` -- and nothing else in it. Everything
//! substantive is here, in a generated file a purge can remove cleanly. The
//! division matters in one direction especially: a **dangling `includedir` is
//! fatal** to every krb5 binary on the host, not only to ours, so the directory
//! must outlive the drop-in and the removal order is the package's to get right.
//!
//! **Generated, never copied and never symlinked.** Samba's provisioner writes
//! its own `krb5.conf` under `/var/lib/samba/private/`, and that file carries no
//! `kdc =` line -- it delegates KDC location to DNS SRV, which works in the
//! Docker Compose deployment only by accident of topology, the realm container's
//! resolver being Samba's own internal DNS. A DC installed from packages
//! generally does not point its resolver at itself, and the failure was measured
//! with the KDC provably listening on `:88`:
//!
//! ```text
//! kinit: Cannot find KDC for realm "KERB.TEST" while getting initial credentials
//! ```
//!
//! One explicit `kdc =` fixes it on every release. Symlinking is refused on its
//! own grounds: Samba's provisioner prints "Merge the contents of this file with
//! your system krb5.conf or replace it with this one. Do not create a symlink!",
//! and `/var/lib/samba/private`'s mode is not ours to rely on.
//!
//! **There is no other channel.** `issuerd` builds its `kinit` subprocess
//! environment with `.env_clear()` on purpose (`crates/kerbridge-issuerd/src/issue.rs`),
//! and `KRB5_CONFIG` is one of the variables that comment names -- so `kinit`
//! always reads `/etc/krb5.conf` and nothing else. A file under `/etc/kerbridge`
//! could not be pointed at.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use kerbridge_core::config::Realm;

/// Where the drop-in lands. `.conf` is not decoration: a file named
/// `kerbridge.local` in this directory was measured to be silently ignored.
pub const DROPIN: &str = "/etc/krb5.conf.d/kerbridge.conf";

/// What the drop-in should say for this config set.
pub fn render(realm: &Realm) -> String {
    let name = &realm.realm;
    let zone = realm.ad_dns_domain();
    let fqdn = format!("{}.{zone}", realm.dc_hostname());
    format!(
        "# Generated by `kbsetup realm` from the KerBridge config set. Edits here are\n\
         # replaced the next time it runs; change realm.toml instead.\n\
         #\n\
         # The explicit `kdc` is the whole point of this file. Samba's own\n\
         # /var/lib/samba/private/krb5.conf has no such line -- it locates the KDC\n\
         # through DNS SRV, which needs this host's resolver to answer for the AD zone.\n\
         # A DC that does not point its resolver at itself then fails with\n\
         # \"Cannot find KDC for realm\" while the KDC is listening.\n\
         \n\
         [libdefaults]\n\
         \tdefault_realm = {name}\n\
         \n\
         [realms]\n\
         \t{name} = {{\n\
         \t\tkdc = {fqdn}\n\
         \t\tadmin_server = {fqdn}\n\
         \t\tdefault_domain = {zone}\n\
         \t}}\n\
         \n\
         [domain_realm]\n\
         \t.{zone} = {name}\n\
         \t{zone} = {name}\n"
    )
}

/// Whether the drop-in on disk already says exactly that.
pub fn current_matches(realm: &Realm, at: &Path) -> bool {
    std::fs::read_to_string(at).is_ok_and(|found| found == render(realm))
}

/// What happened when the drop-in was written.
#[derive(Debug, PartialEq)]
pub enum Wrote {
    /// The file already said exactly this.
    Nothing,
    /// It did not, and now it does.
    Dropin,
    /// The filesystem holding it is read-only, so nothing was written.
    ReadOnly,
}

/// Write it, and say what happened.
///
/// **A read-only filesystem is not a failure here.** The realm container runs
/// with `read_only: true` and a named tmpfs per writable path, so `/etc` cannot
/// be written at all -- and it does not need to be: nothing in that container
/// adds the `includedir` line to `/etc/krb5.conf` that would make a drop-in
/// readable in the first place, and KDC location works there through DNS SRV,
/// the container's resolver being Samba's own internal DNS. Making this fatal
/// killed the realm container on every start, which is how the case was found.
///
/// Every other error stays fatal. This runs as root on a host that is becoming a
/// domain controller: anything else that stops it from writing `/etc` is a
/// problem the operator has to know about before the KDC is in use.
pub fn write(realm: &Realm, at: &Path) -> Result<Wrote> {
    if current_matches(realm, at) {
        return Ok(Wrote::Nothing);
    }
    if let Some(parent) = at.parent()
        && !parent.is_dir()
    {
        match std::fs::create_dir_all(parent) {
            Ok(()) => {}
            Err(e) if read_only(&e) => return Ok(Wrote::ReadOnly),
            Err(e) => return Err(e).with_context(|| format!("creating {}", parent.display())),
        }
    }
    match std::fs::write(at, render(realm)) {
        Ok(()) => {}
        Err(e) if read_only(&e) => return Ok(Wrote::ReadOnly),
        Err(e) => return Err(e).with_context(|| format!("writing {}", at.display())),
    }
    // Every krb5 binary on the host reads this, as whoever ran it.
    std::fs::set_permissions(at, std::os::unix::fs::PermissionsExt::from_mode(0o644))
        .with_context(|| format!("setting the mode of {}", at.display()))?;
    Ok(Wrote::Dropin)
}

/// `EROFS`, and nothing else that merely looks like it. A denied write is a
/// different condition with a different answer, and root meeting one is worth
/// stopping over.
fn read_only(err: &std::io::Error) -> bool {
    err.kind() == std::io::ErrorKind::ReadOnlyFilesystem
}

pub fn path() -> PathBuf {
    PathBuf::from(DROPIN)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn realm_of(toml: &str) -> Realm {
        toml::from_str(toml).expect("the fixture parses")
    }

    fn example() -> Realm {
        realm_of(
            "realm = \"EXAMPLE.SITE\"\n\
             ldap_url = \"ldaps://kerbridge.example.site:636\"\n\
             ldap_ca_file = \"/run/kerbridge/realm-ca.pem\"\n",
        )
    }

    /// The `kdc` line whose absence the module comment measures, spelled with
    /// the DC's own FQDN rather than left to DNS SRV.
    #[test]
    fn the_dropin_states_a_kdc_explicitly() {
        let text = render(&example());
        assert!(text.contains("\t\tkdc = kerbridge.example.site\n"), "{text}");
        assert!(text.contains("\tdefault_realm = EXAMPLE.SITE\n"), "{text}");
    }

    /// The FQDN is built from the two derived values, so a set that states
    /// neither still gets a correct file -- `dc_hostname` falls back to
    /// `ldap_url`'s first label and `ad_dns_domain` to the lowercased realm.
    #[test]
    fn the_kdc_name_follows_a_config_set_that_states_neither_key() {
        let realm = realm_of(
            "realm = \"KERB.TEST\"\n\
             ldap_url = \"ldaps://dc1.kerb.test:636\"\n\
             ldap_ca_file = \"/etc/kerbridge/certs/realm-ca.pem\"\n",
        );
        let text = render(&realm);
        assert!(text.contains("\t\tkdc = dc1.kerb.test\n"), "{text}");
        assert!(text.contains("\t.kerb.test = KERB.TEST\n"), "{text}");
    }

    /// A stated `dc_hostname` wins, which is what a set whose `ldap_url` names
    /// an address rather than a name depends on.
    #[test]
    fn a_stated_dc_hostname_names_the_kdc() {
        let realm = realm_of(
            "realm = \"KERB.TEST\"\n\
             dc_hostname = \"dc9\"\n\
             ldap_url = \"ldaps://192.0.2.10:636\"\n\
             ldap_ca_file = \"/etc/kerbridge/certs/realm-ca.pem\"\n",
        );
        assert!(render(&realm).contains("\t\tkdc = dc9.kerb.test\n"));
    }

    /// The realm container's rootfs is read-only, and the error it raises is
    /// `os error 30`. Recognizing exactly that -- and not a denied write, which
    /// is a different condition -- is what keeps the container alive while
    /// leaving a real failure fatal.
    #[test]
    fn a_read_only_filesystem_is_the_one_error_that_is_not_a_failure() {
        assert!(read_only(&std::io::Error::from_raw_os_error(30)), "EROFS is os error 30 here");
        assert!(!read_only(&std::io::Error::from_raw_os_error(13)), "EACCES is not");
        assert!(!read_only(&std::io::Error::from_raw_os_error(2)), "ENOENT is not");
    }

    /// `verify` reads this comparison at every `ExecStartPre`, so it must be
    /// exact in both directions.
    #[test]
    fn a_file_that_is_not_this_one_does_not_match() {
        let dir = std::env::temp_dir().join(format!("kbsetup-krb5-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let at = dir.join("kerbridge.conf");
        assert!(!current_matches(&example(), &at), "an absent file cannot match");

        assert_eq!(write(&example(), &at).unwrap(), Wrote::Dropin, "the first write lands");
        assert!(current_matches(&example(), &at));
        assert_eq!(
            write(&example(), &at).unwrap(),
            Wrote::Nothing,
            "a second write changes nothing"
        );

        std::fs::write(&at, "[libdefaults]\n\tdefault_realm = OTHER.SITE\n").unwrap();
        assert!(!current_matches(&example(), &at));
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
