//! The trust anchors every LDAPS bind in this workspace uses.
//!
//! Three components reach the same directory over LDAPS -- the broker to resolve
//! an identity, sync to write one, `kbmanage` to diagnose one -- and one
//! implementation serves all three for the reason [`crate::ExternalIdentity`]
//! gives one level up: a second copy that grew a laxer trust decision would
//! still bind, still search, and still look entirely healthy.
//!
//! The crypto provider is named rather than inherited. `ClientConfig::builder()`
//! resolves against a *process-global* default provider -- whatever the
//! dependency graph installed, and a panic on first use when two are compiled
//! in. Naming `ring` here makes the choice a property of this function instead
//! of a property of the build, so no dependency can move it and nothing has to
//! panic to report that it did.

use std::path::Path;
use std::sync::Arc;

use anyhow::{Context, Result, bail};

/// A client configuration that trusts exactly one CA: the realm's own.
///
/// `None` is refused rather than falling back to the OS trust store. Every bind
/// this project makes carries a service-account password, and sync's writes
/// carry `unicodePwd` besides; a directory peer verified against the public web
/// PKI is not the peer that was meant. Samba's autogenerated certificate has no
/// `subjectAltName` and rustls rejects it, so provisioning creates this CA -- see
/// `crates/kerbridge-setup/src/realm.rs` @ `make_tls`.
///
/// The `Arc` is what `ldap3`'s `LdapConnSettings::set_config` takes, and one
/// config is shared across every connection a component makes.
pub fn client_config(ca_pem: Option<&Path>) -> Result<Arc<rustls::ClientConfig>> {
    let Some(path) = ca_pem else {
        bail!("no directory CA configured: refusing to trust an unverified LDAPS peer");
    };
    let pem = std::fs::read(path)
        .with_context(|| format!("reading directory CA from {}", path.display()))?;
    Ok(Arc::new(config_from_pem(&pem, &path.display().to_string())?))
}

/// The trust anchors one PEM file holds, as a store.
///
/// Split out because an LDAPS bind is not the only thing here judging a
/// certificate against an operator-supplied CA: `kbmanage`'s endpoint probe
/// judges the public endpoint's against the same kind of file. A second reader
/// would be a second place for "this file holds no certificate" to be decided
/// differently, and that message is the whole diagnosis when it happens.
pub fn root_store(ca_pem: &Path) -> Result<rustls::RootCertStore> {
    let pem = std::fs::read(ca_pem)
        .with_context(|| format!("reading CA certificates from {}", ca_pem.display()))?;
    store_from_pem(&pem, &ca_pem.display().to_string())
}

/// Split out from the read so the trust rule is testable without a file on
/// disk: the I/O is `std::fs::read`, and that is not what could be wrong here.
/// `label` only names the source in error messages.
fn config_from_pem(pem: &[u8], label: &str) -> Result<rustls::ClientConfig> {
    let store = store_from_pem(pem, label)?;

    Ok(rustls::ClientConfig::builder_with_provider(Arc::new(
        rustls::crypto::ring::default_provider(),
    ))
    .with_safe_default_protocol_versions()
    .context("selecting TLS protocol versions")?
    .with_root_certificates(store)
    .with_no_client_auth())
}

fn store_from_pem(pem: &[u8], label: &str) -> Result<rustls::RootCertStore> {
    use rustls::pki_types::{CertificateDer, pem::PemObject};

    let mut store = rustls::RootCertStore::empty();
    let mut found = 0usize;
    // Blocks that are not certificates are skipped rather than rejected, so a
    // file of the wrong kind reaches the end of this loop having added nothing.
    // That is what the count is for.
    for cert in CertificateDer::pem_slice_iter(pem) {
        let cert = cert.with_context(|| format!("parsing {label}"))?;
        store.add(cert).with_context(|| format!("adding the CA from {label}"))?;
        found += 1;
    }
    // An empty store trusts nothing, so every later bind would fail with a
    // certificate error that names the peer rather than the empty CA file.
    if found == 0 {
        bail!("{label} contains no certificate");
    }

    Ok(store)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A throwaway self-signed CA, so the accept path is exercised against real
    /// DER rather than only the refusals.
    const CA_PEM: &[u8] = include_bytes!("../testdata/test-ca.pem");
    /// Well-formed PEM carrying no certificate -- what `realm.toml`'s
    /// `ldap_ca_file` gets when an operator points it at the realm's key
    /// file, which sits next to the certificate. Any non-`CERTIFICATE` block
    /// reaches the same code path, so this is a public key rather than a
    /// private one: committed key
    /// material is what secret scanners exist to find, and this test needs
    /// none.
    const NOT_A_CERT_PEM: &[u8] = b"-----BEGIN PUBLIC KEY-----\n\
        MCowBQYDK2VwAyEAOI5fqYY0l6QE9sWI6TdhqwKjVLmx1KOG9WrxcZaGGbM=\n\
        -----END PUBLIC KEY-----\n";

    #[test]
    fn refuses_ldaps_without_a_configured_ca() {
        let err = client_config(None).unwrap_err().to_string();
        assert!(err.contains("unverified LDAPS peer"), "{err}");
    }

    #[test]
    fn a_real_ca_yields_a_config() {
        assert!(config_from_pem(CA_PEM, "test-ca.pem").is_ok());
    }

    /// Well-formed PEM that simply holds no certificate. `certs()` skips the
    /// blocks it is not looking for, so this reaches the end with an empty store
    /// rather than failing to parse -- an empty store trusts nothing, and
    /// without the count it would be built and handed out looking fine.
    #[test]
    fn refuses_a_file_carrying_no_certificate() {
        for body in [&b""[..], b"# just a comment\n", NOT_A_CERT_PEM] {
            let err = config_from_pem(body, "cfg.pem").unwrap_err().to_string();
            assert!(err.contains("contains no certificate"), "{err}");
        }
    }

    /// A truncated block is the other half, and it must not read as an empty
    /// file: that would turn a corrupted CA into the same message as a missing
    /// one, and send the operator looking for the wrong mistake.
    #[test]
    fn a_malformed_block_is_a_parse_error_and_names_the_file() {
        let truncated = b"-----BEGIN CERTIFICATE-----\nMIIB\n";
        let err = config_from_pem(truncated, "cfg.pem").unwrap_err();
        let text = format!("{err:#}");
        assert!(text.contains("parsing cfg.pem"), "{text}");
        assert!(!text.contains("contains no certificate"), "{text}");
    }

    /// Two CAs in one file is a legitimate rollover shape, and both must land in
    /// the store -- silently keeping the first would break the bind on the day
    /// the directory switched to the second.
    #[test]
    fn accepts_a_bundle_and_keeps_every_certificate_in_it() {
        let mut bundle = CA_PEM.to_vec();
        bundle.extend_from_slice(CA_PEM);
        assert!(config_from_pem(&bundle, "bundle.pem").is_ok());
    }
}
