//! The Samba side: reading current state out of its IdP-specific OU, and applying a
//! plan over delegated LDAPS as its `svc-kerbridge-sync-<source>` identity.
//!
//! Reads mirror the sync spike's `dump_current`; writes mirror its `apply_plan`,
//! both proven against a live disposable Samba by the directory-sync spike. Only
//! objects carrying a `kb1` identity for this instance's own
//! [`Source`] are treated as managed; anything else under the OU is reported as
//! unmanaged and never touched -- which is also what keeps a second source's
//! objects safe if the two are ever pointed at one OU. The TLS setup is the
//! broker's: the realm's own CA, because Samba's autogenerated certificate has
//! no SAN and rustls rejects it.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use ldap3::adapters::{Adapter, EntriesOnly, PagedResults};
use ldap3::{LdapConnAsync, LdapConnSettings, Mod, ResultEntry, Scope, SearchEntry};

use kerbridge_core::state::{
    GROUP_TYPE_GLOBAL_SECURITY, ROLE_ADMISSION, UAC_DISABLED, UAC_ENABLED,
};

use kerbridge_core::dn::parent_of;
use kerbridge_core::sam;
use kerbridge_core::secret::Secret;
use kerbridge_core::{ExternalIdentity, Source};

use crate::planner::{Current, CurrentGroup, CurrentUser, Op, OrderedMap, Plan};

pub struct Directory {
    url: String,
    base_dn: String,
    idp_ou: String,
    bind_dn: String,
    bind_password: Secret,
    tls: Arc<rustls::ClientConfig>,
    timeout: Duration,
}

/// The only attributes [`Op::SetAttr`] may write.
///
/// `SetAttr` is the one whole-attribute `Mod::Replace` taking an arbitrary
/// attribute name, and the planner emits it for exactly these three. Aimed at a
/// multi-valued attribute it would replace *every* value: on `extensionName`
/// that is every state marker and every device grant on the object, wiped in one
/// write and recoverable only from a backup. The planner does not do that today
/// and a test says so; this is what makes it impossible rather than merely
/// absent, since the next call site is the one nobody will remember to check.
const SETTABLE_ATTRS: [&str; 3] = ["sAMAccountName", "userPrincipalName", "displayName"];

/// The tally a cycle logs and audits: what was applied and what failed. A failed
/// op is recorded and the rest proceed -- one bad write must not strand the others.
///
/// Both halves name the object rather than counting it -- the audit file keeps
/// these, and a count answers "how much changed" where the question a year later
/// is "to whom".
#[derive(Debug, Default)]
pub struct ApplyReport {
    /// One `<op> <dn>` per write that succeeded, in the order the plan ran them.
    pub applied: Vec<String>,
    /// One `<dn>: <error>` per write that did not.
    pub failures: Vec<String>,
}

impl Directory {
    pub fn new(
        url: String,
        base_dn: String,
        idp_ou: String,
        bind_dn: String,
        bind_password: Secret,
        ca_pem: &std::path::Path,
        timeout: Duration,
    ) -> Result<Self> {
        Ok(Self {
            url,
            base_dn,
            idp_ou,
            bind_dn,
            bind_password,
            tls: kerbridge_core::tls::client_config(Some(ca_pem))?,
            timeout,
        })
    }

    async fn connect(&self) -> Result<ldap3::Ldap> {
        let settings =
            LdapConnSettings::new().set_config(self.tls.clone()).set_conn_timeout(self.timeout);
        let (conn, mut ldap) = LdapConnAsync::with_settings(settings, &self.url)
            .await
            .with_context(|| format!("connecting to {}", self.url))?;
        ldap3::drive!(conn);
        ldap.simple_bind(&self.bind_dn, self.bind_password.expose())
            .await
            .context("binding to the realm directory")?
            .success()
            .with_context(|| format!("binding as {}", self.bind_dn))?;
        Ok(ldap)
    }

    /// Read every managed user and group under the IdP-specific OU, plus a
    /// domain-wide `sAMAccountName` scan for collision-safe name allocation.
    pub async fn read_current(&self, source: &Source) -> Result<Current> {
        let mut ldap = self.connect().await?;
        let result = self.read_current_inner(&mut ldap, source).await;
        let _ = ldap.unbind().await;
        result
    }

    async fn read_current_inner(&self, ldap: &mut ldap3::Ldap, source: &Source) -> Result<Current> {
        let entries = search_paged(
            ldap,
            &self.idp_ou,
            "(|(objectClass=user)(objectClass=group))",
            vec![
                "sAMAccountName",
                "displayName",
                "userAccountControl",
                "msDS-ExternalDirectoryObjectId",
                "extensionName",
                "member",
                "objectClass",
            ],
        )
        .await
        .context("reading the IdP-specific OU")?;

        let mut users: Vec<(String, CurrentUser)> = Vec::new();
        let mut groups: Vec<(String, CurrentGroup)> = Vec::new();
        let mut unmanaged_dns = Vec::new();
        let mut managed_sams: HashSet<String> = HashSet::new();

        for entry in entries {
            let e = SearchEntry::construct(entry);
            let identity = first(&e, "msDS-ExternalDirectoryObjectId");
            // Decoded by the one implementation, never parsed here. A value this
            // side accepts and the broker's `decode` refuses is the worst
            // outcome available: the object counts as managed, keys under a
            // subject nothing desires, and is retired and recreated with a fresh
            // SID -- which strands every file its owner has under `idmap_rid`.
            // Refusing it instead leaves the DN in `unmanaged_dns`, reported and
            // untouched, which is what an unreadable identity deserves.
            let decoded = match identity.as_deref().map(ExternalIdentity::decode) {
                Some(Ok(id)) => Some(id),
                Some(Err(why)) => {
                    eprintln!(
                        "[sync] ALERT: {} carries an identity this tool cannot read ({why}); \
                         leaving it untouched",
                        e.dn
                    );
                    None
                }
                None => None,
            };
            let Some(id) = decoded.filter(|id| id.source() == source) else {
                unmanaged_dns.push(e.dn.clone());
                continue;
            };
            let identity = identity.expect("a decoded identity was present");
            let oid = id.subject().to_owned();
            let sam = first(&e, "sAMAccountName").unwrap_or_default();
            managed_sams.insert(sam::fold(&sam));
            let markers = e.attrs.get("extensionName").cloned().unwrap_or_default();
            let is_group =
                e.attrs.get("objectClass").is_some_and(|c| c.iter().any(|v| v == "group"));
            if is_group {
                groups.push((
                    oid,
                    CurrentGroup {
                        dn: e.dn.clone(),
                        sam,
                        display_name: first(&e, "displayName").unwrap_or_else(|| cn_of(&e.dn)),
                        members: members_of(ldap, &e).await?,
                        markers,
                        identity,
                    },
                ));
            } else {
                let uac: u32 =
                    first(&e, "userAccountControl").and_then(|v| v.parse().ok()).unwrap_or(0);
                users.push((
                    oid,
                    CurrentUser {
                        dn: e.dn.clone(),
                        sam,
                        display_name: first(&e, "displayName"),
                        enabled: uac & 0x0002 == 0,
                        markers,
                        identity,
                    },
                ));
            }
        }

        let foreign_sams = self.foreign_sams(ldap, &managed_sams).await?;
        Ok(Current {
            users: OrderedMap(users),
            groups: OrderedMap(groups),
            foreign_sams,
            unmanaged_dns,
        })
    }

    /// Every `sAMAccountName` in the domain that sync does not manage -- the
    /// namespace `alloc_names` must avoid colliding with.
    ///
    /// `managed` holds `sam::fold` keys, so the exclusion has to fold too: an
    /// object whose stored name differs in case from the folded form would
    /// otherwise come back as *foreign*, and sync would then plan around a
    /// collision with itself.
    async fn foreign_sams(
        &self,
        ldap: &mut ldap3::Ldap,
        managed: &HashSet<String>,
    ) -> Result<Vec<String>> {
        let entries = search_paged(
            ldap,
            &self.base_dn,
            "(|(objectClass=user)(objectClass=group))",
            vec!["sAMAccountName"],
        )
        .await
        .context("reading domain sAMAccountNames")?;
        Ok(entries
            .into_iter()
            .filter_map(|e| first(&SearchEntry::construct(e), "sAMAccountName"))
            .filter(|s| !managed.contains(&sam::fold(s)))
            .collect())
    }

    /// Apply a plan in order. `markers` resolves `clear_marker` ops to the exact
    /// values to delete; it comes from the same `read_current` the plan was made
    /// against.
    pub async fn apply(
        &self,
        plan: &Plan,
        markers: &HashMap<String, Vec<String>>,
    ) -> Result<ApplyReport> {
        let mut ldap = self.connect().await?;
        let mut report = ApplyReport::default();
        for op in &plan.ops {
            match self.apply_one(&mut ldap, op, markers).await {
                Ok(()) => report.applied.push(format!("{} {}", op.kind(), op.dn())),
                Err(e) => report.failures.push(format!("{}: {e:#}", op.dn())),
            }
        }
        let _ = ldap.unbind().await;
        Ok(report)
    }

    /// The precondition the planner's alert says is re-checked at apply time,
    /// actually re-checked at apply time.
    ///
    /// Stamping the role marker is what makes a group *the* admission group, and
    /// the planner only plans it after seeing no marker anywhere. That read
    /// happened a whole cycle earlier -- a source read, a plan, and every op before
    /// this one ago -- and the only thing that could have marked a group in
    /// between is a writer the planner cannot see: an operator, or a second sync.
    /// Two marked groups is the ambiguity the broker fails closed on, so the
    /// cheap read here is what keeps a race from taking the realm down until
    /// someone finds the extra marker by hand.
    async fn assert_no_role_marker_yet(&self, ldap: &mut ldap3::Ldap) -> Result<()> {
        let filter = format!("(extensionName={ROLE_ADMISSION})");
        let (entries, _) = ldap
            .search(&self.idp_ou, Scope::Subtree, &filter, vec!["1.1"])
            .await
            .context("re-checking the role marker before creating the admission group")?
            .success()
            .context("re-checking the role marker before creating the admission group")?;
        if let Some(e) = entries.first() {
            bail!(
                "refusing to mark a second admission group: {} already carries {ROLE_ADMISSION}. \
                 It was not there when this cycle was planned, so something else wrote it",
                SearchEntry::construct(e.clone()).dn
            );
        }
        Ok(())
    }

    async fn apply_one(
        &self,
        ldap: &mut ldap3::Ldap,
        op: &Op,
        markers: &HashMap<String, Vec<String>>,
    ) -> Result<()> {
        match op {
            Op::CreateUser { dn, sam, upn, display_name, enabled, identity } => {
                let uac = if *enabled { UAC_ENABLED } else { UAC_DISABLED };
                add(
                    ldap,
                    dn,
                    &[
                        ("objectClass", vec![b"user".to_vec()]),
                        ("sAMAccountName", vec![bytes(sam)]),
                        ("userPrincipalName", vec![bytes(upn)]),
                        ("displayName", vec![bytes(display_name)]),
                        ("userAccountControl", vec![bytes(uac)]),
                        ("unicodePwd", vec![unicode_pwd(&random_password())]),
                        ("msDS-ExternalDirectoryObjectId", vec![bytes(identity)]),
                    ],
                )
                .await
            }
            Op::CreateGroup { dn, sam, identity, role_marker } => {
                let mut attrs = vec![
                    ("objectClass", vec![b"group".to_vec()]),
                    ("sAMAccountName", vec![bytes(sam)]),
                    ("groupType", vec![bytes(GROUP_TYPE_GLOBAL_SECURITY)]),
                    ("msDS-ExternalDirectoryObjectId", vec![bytes(identity)]),
                ];
                if let Some(marker) = role_marker {
                    self.assert_no_role_marker_yet(ldap).await?;
                    attrs.push(("extensionName", vec![bytes(marker)]));
                }
                add(ldap, dn, &attrs).await
            }
            Op::AddMember { dn, member } => {
                modify(ldap, dn, vec![Mod::Add(bytes("member"), one(member))]).await
            }
            Op::RemoveMember { dn, member } => {
                modify(ldap, dn, vec![Mod::Delete(bytes("member"), one(member))]).await
            }
            Op::EnableUser { dn } => replace_uac(ldap, dn, UAC_ENABLED).await,
            Op::DisableUser { dn } => replace_uac(ldap, dn, UAC_DISABLED).await,
            Op::SetAttr { dn, attr, value } => {
                if !SETTABLE_ATTRS.contains(&attr.as_str()) {
                    bail!(
                        "refusing SetAttr on {attr}: this is the only whole-attribute Replace \
                         taking an arbitrary name, and it may write nothing outside {SETTABLE_ATTRS:?}"
                    );
                }
                modify(ldap, dn, vec![Mod::Replace(bytes(attr), one(value))]).await
            }
            Op::SetMarker { dn, value } | Op::SetRoleMarker { dn, value } => {
                modify(ldap, dn, vec![Mod::Add(bytes("extensionName"), one(value))]).await
            }
            Op::ClearMembers { dn, keep } => {
                // One `Replace` down to the members sync does not own, rather
                // than `Replace(member, ∅)`: the empty set takes locally nested
                // members with it, which is the one thing this op promises not
                // to do.
                let keep: HashSet<Vec<u8>> = keep.iter().map(|m| bytes(m)).collect();
                modify(ldap, dn, vec![Mod::Replace(bytes("member"), keep)]).await
            }
            Op::ClearMarker { dn, prefix } => {
                let to_delete: HashSet<Vec<u8>> = markers
                    .get(dn)
                    .into_iter()
                    .flatten()
                    .filter(|m| m.starts_with(prefix.as_str()))
                    .map(|m| bytes(m))
                    .collect();
                if to_delete.is_empty() {
                    return Ok(());
                }
                modify(ldap, dn, vec![Mod::Delete(bytes("extensionName"), to_delete)]).await
            }
            Op::Rename { dn, new_cn, set_display_name, set_sam, set_upn } => {
                let rdn = format!("CN={new_cn}");
                ldap.modifydn(dn, &rdn, true, None)
                    .await
                    .context("renaming")?
                    .success()
                    .context("rename was refused")?;
                // No `newsuperior`, so the object keeps its parent -- take the
                // follow-up DN from where it actually is, not from `idp_ou`.
                let new_dn = format!("{rdn},{}", parent_of(dn));
                if let Some(name) = set_display_name {
                    modify(ldap, &new_dn, vec![Mod::Replace(bytes("displayName"), one(name))])
                        .await?;
                }
                if let Some(sam) = set_sam {
                    modify(ldap, &new_dn, vec![Mod::Replace(bytes("sAMAccountName"), one(sam))])
                        .await?;
                }
                if let Some(upn) = set_upn {
                    modify(ldap, &new_dn, vec![Mod::Replace(bytes("userPrincipalName"), one(upn))])
                        .await?;
                }
                Ok(())
            }
        }
    }
}

/// Entries asked for per page. The server caps a page at its own `MaxPageSize`
/// whatever this says, so it only decides how few round trips a small realm costs.
const PAGE_SIZE: i32 = 1000;

/// A subtree search that reads past the server's `MaxPageSize`, for the two
/// reads whose result set grows with the realm.
///
/// Measured on the bench (2026-08-26, disposable realm, 12 055 users and groups
/// against the default `MaxPageSize=1000`): an unpaged search returns every one
/// of them with `rc=0`, and Samba ignores the client's own `sizeLimit` as well.
/// So on this server the ceiling is inert and the control below changes nothing
/// -- the same finding, and the same answer, as `MaxValRange` in `members_of`.
///
/// It is here for the server that does enforce it, which is every Windows DC and
/// could be a later Samba. That one answers a larger result set with
/// `sizeLimitExceeded` and the first `MaxPageSize` entries, and `foreign_sams`
/// counts every user and group in the realm -- so the cycle would stop at 1 001
/// objects and never run again. A server that answered short with `rc=0` instead
/// would be worse and silent: sync would read a `sAMAccountName` as free when the
/// realm already holds it. The control is not critical, so a server that does not
/// implement it answers exactly as it does today.
async fn search_paged(
    ldap: &mut ldap3::Ldap,
    base: &str,
    filter: &str,
    attrs: Vec<&str>,
) -> Result<Vec<ResultEntry>> {
    // `EntriesOnly` before `PagedResults`, the order ldap3's own example uses:
    // it keeps referrals out of the entries.
    let adapters: Vec<Box<dyn Adapter<_, _>>> =
        vec![Box::new(EntriesOnly::new()), Box::new(PagedResults::new(PAGE_SIZE))];
    let mut stream =
        ldap.streaming_search_with(adapters, base, Scope::Subtree, filter, attrs).await?;
    let mut entries = Vec::new();
    while let Some(entry) = stream.next().await? {
        entries.push(entry);
    }
    // A refusal on any page fails the cycle. The pages that did arrive are not
    // the realm, and returning them as if they were is the bug paging prevents.
    stream.finish().await.success().context("the search was refused")?;
    Ok(entries)
}

/// Every `member` of a group entry, following ranged retrieval when the server
/// answers with `member;range=lo-hi` instead of the attribute that was asked for.
///
/// Measured on the bench (2026-07-28, disposable realm,
/// one 6 000-member group): a plain `member` request returns all 6 000 values.
/// The default query policy carries `MaxValRange=1500` and lowering it to 100
/// changes nothing, so on this server the limit is inert and this walk never
/// runs. What is not inert is the ranging itself -- `member;range=0-1499` returns
/// exactly 1500 values under that key, `member;range=500-*` returns the rest
/// under *that* key, and a start past the end returns no `member` attribute at
/// all. All three shapes are handled below.
///
/// The walk exists because a server that does enforce the limit, which is every
/// Windows DC and could be a later Samba, answers a large group with
/// `member;range=0-1499` -- a key `attrs.get("member")` does not match. The group
/// would read as having no members, every removal from it would be planned as
/// already done, and revocation would break precisely when a group got large,
/// silently.
async fn members_of(ldap: &mut ldap3::Ldap, entry: &SearchEntry) -> Result<Vec<String>> {
    if let Some(members) = entry.attrs.get("member") {
        return Ok(members.clone());
    }
    let Some((mut members, mut next)) = range_chunk(&entry.attrs)? else {
        return Ok(Vec::new());
    };
    while let Some(lo) = next {
        let attr = format!("member;range={lo}-*");
        let (entries, _) = ldap
            .search(&entry.dn, Scope::Base, "(objectClass=*)", vec![attr.as_str()])
            .await
            .with_context(|| format!("reading {attr} of {}", entry.dn))?
            .success()
            .with_context(|| format!("reading {attr} of {} was refused", entry.dn))?;
        let Some(chunk) = entries.into_iter().next() else {
            bail!("{} vanished while reading {attr}", entry.dn);
        };
        let chunk = SearchEntry::construct(chunk);
        match range_chunk(&chunk.attrs)? {
            Some((values, more)) => {
                members.extend(values);
                // `lo-*` is answered with a range starting at `lo`, so the next
                // start is always past it. A server that says otherwise is not
                // making progress, and looping on it would never end.
                next = match more {
                    Some(n) if n <= lo => {
                        bail!("{} answered range {lo}-* with a chunk ending at {n}", entry.dn)
                    }
                    other => other,
                };
            }
            // No ranged key came back: the server answered the tail plainly, or
            // there was no tail. Either way there is nothing further to ask for.
            None => {
                members.extend(chunk.attrs.get("member").cloned().unwrap_or_default());
                break;
            }
        }
    }
    Ok(members)
}

/// The values under an entry's `member;range=lo-hi` key, and where the next
/// chunk starts -- `None` when `hi` is `*`, which is the server saying this was
/// the last of them.
fn range_chunk(attrs: &HashMap<String, Vec<String>>) -> Result<Option<(Vec<String>, Option<u32>)>> {
    for (key, values) in attrs {
        let lower = key.to_ascii_lowercase();
        let Some(bounds) = lower.strip_prefix("member;range=") else {
            continue;
        };
        let hi = bounds.split_once('-').map(|(_, hi)| hi).unwrap_or_default();
        let next = match hi {
            "*" => None,
            n => Some(
                n.parse::<u32>().with_context(|| format!("upper bound of {key}"))?.wrapping_add(1),
            ),
        };
        return Ok(Some((values.clone(), next)));
    }
    Ok(None)
}

/// Marker lookup keyed by DN, built from a just-read `Current` so `clear_marker`
/// knows exactly which values to delete.
pub fn marker_index(current: &Current) -> HashMap<String, Vec<String>> {
    current
        .users
        .iter()
        .map(|(_, u)| (u.dn.clone(), u.markers.clone()))
        .chain(current.groups.iter().map(|(_, g)| (g.dn.clone(), g.markers.clone())))
        .collect()
}

async fn add(ldap: &mut ldap3::Ldap, dn: &str, attrs: &[(&str, Vec<Vec<u8>>)]) -> Result<()> {
    let attrs: Vec<(Vec<u8>, HashSet<Vec<u8>>)> =
        attrs.iter().map(|(name, vals)| (bytes(name), vals.iter().cloned().collect())).collect();
    ldap.add(dn, attrs).await.context("adding")?.success().context("add was refused")?;
    Ok(())
}

async fn modify(ldap: &mut ldap3::Ldap, dn: &str, mods: Vec<Mod<Vec<u8>>>) -> Result<()> {
    ldap.modify(dn, mods).await.context("modifying")?.success().context("modify was refused")?;
    Ok(())
}

async fn replace_uac(ldap: &mut ldap3::Ldap, dn: &str, uac: &str) -> Result<()> {
    modify(ldap, dn, vec![Mod::Replace(bytes("userAccountControl"), one(uac))]).await
}

fn bytes(s: &str) -> Vec<u8> {
    s.as_bytes().to_vec()
}

fn one(s: &str) -> HashSet<Vec<u8>> {
    HashSet::from([bytes(s)])
}

/// A random undisclosed password. The account's key is what issuance uses;
/// nothing ever needs the password that generated it.
///
/// Generated by `kerbridge_core::password`, the one implementation of "a
/// password Samba will accept". The `Kb1-` form is compatibility, not taste:
/// every account this crate has created binds with one.
fn random_password() -> Secret {
    kerbridge_core::password::generate(kerbridge_core::password::Alphabet::Base64Url)
}

/// `unicodePwd` is the password wrapped in double quotes, UTF-16LE encoded. Over
/// LDAPS the transport is already encrypted, which is what lets it be set at all.
fn unicode_pwd(password: &Secret) -> Vec<u8> {
    format!("\"{}\"", password.expose()).encode_utf16().flat_map(u16::to_le_bytes).collect()
}

fn first(entry: &SearchEntry, attr: &str) -> Option<String> {
    entry.attrs.get(attr).and_then(|v| v.first()).cloned()
}

/// The CN value out of a DN's first RDN -- the display-name fallback for a group
/// with no `displayName`, matching the spike's `dump_current`.
fn cn_of(dn: &str) -> String {
    dn.split(',').next().and_then(|rdn| rdn.strip_prefix("CN=")).unwrap_or(dn).to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unicode_pwd_is_quoted_utf16le() {
        let out = unicode_pwd(&Secret::new("Ab1"));
        // ", A, b, 1, " -> five UTF-16LE code units, low byte then zero high byte.
        assert_eq!(out, vec![0x22, 0, b'A', 0, b'b', 0, b'1', 0, 0x22, 0]);
    }

    /// The complexity rule itself is `kerbridge_core::password`'s to hold, over
    /// thousands of draws. What is this crate's is the form: a delegation that
    /// silently changed the alphabet would be invisible until a realm directory
    /// refused a password.
    #[test]
    fn random_password_is_still_the_form_this_crate_writes() {
        let a = random_password();
        let b = random_password();
        let (a, b) = (a.expose(), b.expose());
        assert!(a.starts_with("Kb1-"), "{a}");
        assert!(a.len() >= 8, "{a}");
        assert_ne!(a, b, "two draws must differ");
    }

    #[test]
    fn cn_fallback_reads_the_first_rdn() {
        assert_eq!(cn_of("CN=proj-x,OU=Entra,DC=example,DC=site"), "proj-x");
        assert_eq!(cn_of("weird"), "weird");
    }

    fn attrs(pairs: &[(&str, &[&str])]) -> HashMap<String, Vec<String>> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_owned(), v.iter().map(|s| (*s).to_owned()).collect()))
            .collect()
    }

    /// The whole point: a ranged answer must not read as a group with no members.
    #[test]
    fn a_ranged_answer_is_a_chunk_and_a_plain_one_is_not() {
        assert!(range_chunk(&attrs(&[("member", &["CN=a,OU=Entra,DC=x"])])).unwrap().is_none());
        assert!(range_chunk(&attrs(&[])).unwrap().is_none());

        let (values, next) =
            range_chunk(&attrs(&[("member;range=0-1499", &["CN=a,OU=Entra,DC=x"])]))
                .unwrap()
                .expect("a range key is a chunk");
        assert_eq!(values, vec!["CN=a,OU=Entra,DC=x"]);
        assert_eq!(next, Some(1500), "the next chunk starts one past the upper bound");
    }

    /// `*` is the server saying that was the last of them; the attribute
    /// description's case is not the server's promise to keep.
    #[test]
    fn a_star_bound_ends_the_walk_whatever_its_spelling() {
        let (_, next) = range_chunk(&attrs(&[("Member;Range=1500-*", &["CN=b,OU=Entra,DC=x"])]))
            .unwrap()
            .expect("a range key is a chunk");
        assert_eq!(next, None);
    }

    #[test]
    fn an_unreadable_upper_bound_is_an_error_and_not_an_empty_group() {
        assert!(range_chunk(&attrs(&[("member;range=0-lots", &["CN=c,OU=Entra,DC=x"])])).is_err());
    }
}
