//! The macOS arm of [`super`]: `res_query` from libresolv, and the resolver's
//! own search list.
//!
//! **The answer is parsed here.** libresolv ships `res_query` and `dn_expand` in
//! its export list but not `ns_initparse`/`ns_parserr`, so the response is walked
//! by hand -- a fixed 12-byte header, the question section skipped, then one pass
//! over the answers keeping the SRVs. `dn_expand` does the only genuinely fiddly
//! part, which is following the compression pointers a target name arrives in.

use std::ffi::{CString, c_char, c_int, c_uchar};

use super::Srv;

const C_IN: c_int = 1;
const T_SRV: c_int = 33;
/// Enough for any plausible answer; a response longer than this is truncated by
/// the resolver and treated as no answer, which is the same as no record.
const ANSWER_MAX: usize = 4096;
/// `NS_MAXDNAME`, the longest name `dn_expand` can produce.
const NAME_MAX: usize = 1025;

#[link(name = "resolv")]
unsafe extern "C" {
    fn res_query(
        name: *const c_char,
        class: c_int,
        rtype: c_int,
        answer: *mut c_uchar,
        anslen: c_int,
    ) -> c_int;
    fn dn_expand(
        msg: *const c_uchar,
        eom: *const c_uchar,
        src: *const c_uchar,
        dst: *mut c_char,
        dstsiz: c_int,
    ) -> c_int;
}

/// The DNS domains this machine is in, from the resolver's search list.
///
/// `/etc/resolv.conf` carries its own notice that it is not what resolves
/// hostnames on macOS, and that is true -- but it is generated by `configd` from
/// the same configuration `res_query` below consults, and the global search list
/// it holds already merges every interface's domains. That merge is what had to
/// be dug out of per-adapter registry keys on Windows; here it is done for us.
pub fn own_domains() -> Vec<String> {
    let Ok(text) = std::fs::read_to_string("/etc/resolv.conf") else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        // `domain` names one; `search` names up to six, whitespace-separated.
        // A later `search` replaces an earlier one for the resolver, but both are
        // kept here: an extra zone to ask costs one NXDOMAIN.
        if let Some(rest) = line.strip_prefix("search ").or_else(|| line.strip_prefix("domain ")) {
            out.extend(rest.split_whitespace().map(str::to_owned));
        }
    }
    out
}

/// One SRV query. Anything other than a successful answer -- NXDOMAIN, no
/// resolver, a timeout -- is an empty result: this is a lookup that is *expected*
/// to find nothing on most networks.
pub fn lookup_srv(name: &str) -> Vec<Srv> {
    let Ok(name) = CString::new(name) else {
        return Vec::new();
    };
    let mut answer = vec![0u8; ANSWER_MAX];
    let len =
        unsafe { res_query(name.as_ptr(), C_IN, T_SRV, answer.as_mut_ptr(), ANSWER_MAX as c_int) };
    if len <= 0 {
        return Vec::new();
    }
    parse(&answer[..len as usize])
}

/// Walk a DNS response, keeping the SRV records in the answer section.
///
/// Every step is bounds-checked against the message the resolver returned, and a
/// malformed one stops the walk rather than being reported: a broken answer and
/// no answer lead to the same place, which is the next domain to try.
fn parse(msg: &[u8]) -> Vec<Srv> {
    let mut out = Vec::new();
    if msg.len() < 12 {
        return out;
    }
    let questions = be16(msg, 4);
    let answers = be16(msg, 6);

    let mut at = 12usize;
    for _ in 0..questions {
        let Some(next) = skip_name(msg, at) else {
            return out;
        };
        // QTYPE and QCLASS.
        at = next + 4;
    }
    for _ in 0..answers {
        let Some(next) = skip_name(msg, at) else {
            return out;
        };
        at = next;
        // TYPE, CLASS, TTL, RDLENGTH.
        if at + 10 > msg.len() {
            return out;
        }
        let rtype = be16(msg, at);
        let rdlen = be16(msg, at + 8) as usize;
        at += 10;
        if at + rdlen > msg.len() {
            return out;
        }
        // priority, weight, port, then the target name.
        if rtype as c_int == T_SRV
            && rdlen >= 7
            && let Some(target) = expand(msg, at + 6)
        {
            out.push(Srv {
                target,
                priority: be16(msg, at),
                weight: be16(msg, at + 2),
                port: be16(msg, at + 4),
            });
        }
        at += rdlen;
    }
    out
}

fn be16(msg: &[u8], at: usize) -> u16 {
    u16::from_be_bytes([msg[at], msg[at + 1]])
}

/// The offset just past the name starting at `at`, following compression
/// pointers to measure it but not to read it.
fn skip_name(msg: &[u8], mut at: usize) -> Option<usize> {
    loop {
        let len = *msg.get(at)? as usize;
        match len {
            // Root label: the name ends here.
            0 => return Some(at + 1),
            // A pointer is two bytes and always terminal.
            _ if len & 0xc0 == 0xc0 => return (at + 1 < msg.len()).then_some(at + 2),
            _ => at += len + 1,
        }
    }
}

/// The name at `at`, with compression pointers followed.
fn expand(msg: &[u8], at: usize) -> Option<String> {
    let mut buf = vec![0 as c_char; NAME_MAX];
    let n = unsafe {
        dn_expand(
            msg.as_ptr(),
            msg.as_ptr().add(msg.len()),
            msg.as_ptr().add(at),
            buf.as_mut_ptr(),
            NAME_MAX as c_int,
        )
    };
    if n < 0 {
        return None;
    }
    let bytes: Vec<u8> = buf.iter().take_while(|&&c| c != 0).map(|&c| c as u8).collect();
    String::from_utf8(bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A real `_kerbridge._tcp` answer, byte for byte, with the target reached
    /// through a compression pointer back into the question -- which is how every
    /// resolver actually encodes it, and the reason `dn_expand` is called rather
    /// than the name read straight out of the record.
    fn answer() -> Vec<u8> {
        let mut m = Vec::new();
        m.extend([0x12, 0x34]); // id
        m.extend([0x81, 0x80]); // response, recursion available, rcode 0
        m.extend([0x00, 0x01]); // qdcount
        m.extend([0x00, 0x01]); // ancount
        m.extend([0x00, 0x00, 0x00, 0x00]); // nscount, arcount
        // _kerbridge._tcp.example.site
        let question = b"\x0a_kerbridge\x04_tcp\x07example\x04site\x00";
        m.extend(question);
        m.extend([0x00, 0x21, 0x00, 0x01]); // SRV, IN
        m.extend([0xc0, 0x0c]); // name: pointer to offset 12
        m.extend([0x00, 0x21, 0x00, 0x01]); // SRV, IN
        m.extend([0x00, 0x00, 0x01, 0x2c]); // ttl
        let rdata_at = m.len();
        m.extend([0x00, 0x00]); // rdlength, filled in below
        m.extend([0x00, 0x00]); // priority 0
        m.extend([0x00, 0x64]); // weight 100
        m.extend([0x01, 0xbb]); // port 443
        // kerbridge, then a pointer to "example.site" inside the question.
        m.extend(b"\x09kerbridge");
        m.extend([0xc0, (12 + 16) as u8]); // "\x07example\x04site\x00" starts there
        let rdlen = (m.len() - rdata_at - 2) as u16;
        m[rdata_at..rdata_at + 2].copy_from_slice(&rdlen.to_be_bytes());
        m
    }

    #[test]
    fn reads_a_compressed_srv_answer() {
        let records = parse(&answer());
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].target, "kerbridge.example.site");
        assert_eq!(records[0].port, 443);
        assert_eq!(records[0].priority, 0);
        assert_eq!(records[0].weight, 100);
    }

    /// A response cut off mid-record must yield nothing rather than read past it.
    #[test]
    fn a_truncated_answer_is_no_answer() {
        let full = answer();
        for cut in 12..full.len() {
            let _ = parse(&full[..cut]);
        }
        assert!(parse(&full[..full.len() - 4]).is_empty());
        assert!(parse(&[]).is_empty());
    }
}
