use super::Strings;

pub(super) static DE: Strings = Strings {
    lang_tag: "de",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Status öffnen",
    menu_settings: "Einstellungen…",
    menu_help: "Hilfe",
    menu_quit: "NAS Access beenden",

    cond_working: "Zugriff OK",
    cond_flaky: "Erneuerung unsicher",
    cond_will_stop: "Zugriff läuft ab",
    cond_stopped: "Kein Zugriff",
    cond_off: "Aus",

    id_signed_in_as: "Angemeldet als {account}",
    id_working_as: "Arbeitet als {account}",

    access_ends_in: "Zugriff endet in {duration}",
    grant_expires_in: "Autorisierung läuft in {days} ab",
    dur_hours_minutes: "{h} Std. {m} Min.",
    dur_minutes: "{m} Min.",
    dur_under_a_minute: "unter einer Minute",
    dur_one_day: "1 Tag",
    dur_days: "{d} Tage",

    blk_no_broker_url: "Broker-URL nicht konfiguriert",
    blk_network_error: "{broker} nicht erreichbar",
    blk_realm_unknown: "Keine Einstellungen von {broker}",
    blk_realm_not_registered: "Windows nicht für {realm} eingerichtet",
    blk_no_supply: "Browser-Anmeldung erforderlich",
    blk_no_grant: "Dieses Gerät ist nicht autorisiert, als {account} zu arbeiten",
    blk_grant_refused: "Ihre Organisation hat diese Autorisierung abgelehnt",
    blk_refused: "Ihr Konto wurde abgelehnt",
    blk_ntlm_fallback: "Netzlaufwerke funktionieren nicht mehr (NTLM)",

    details_heading: "Kerberos-Details",
    meter_label: "Zugriff gültig für",
    d_realm: "Realm",
    d_source: "Quelle",
    d_ticket: "Ticket",
    d_ticket_value: "Verlängerbar · endet um {time}",
    d_ticket_value_norenew: "Endet um {time}",
    d_supply: "Erneuert über",
    d_supply_grant: "die Autorisierung dieses Geräts",
    d_supply_wam: "Ihr Windows-Konto",
    d_supply_browser: "Ihre Browser-Anmeldung",
    d_supply_none: "nichts — braucht Sie",
    d_next: "Nächster Versuch",

    err_sign_off_failed: "Abmelden fehlgeschlagen: Windows hat das Löschen der Tickets dieses Realms verweigert. Offene Freigaben funktionieren möglicherweise weiter.",
    signed_off_note: "Abgemeldet. Bereits geöffnete Netzlaufwerke funktionieren möglicherweise weiter, bis Sie sie schließen oder dieses Gerät neu starten.",
    granted_note: "Dieses Gerät erhält den Zugriff jetzt selbstständig. Ihr Browser ist weiterhin bei {idp} angemeldet — eine Abmeldung dort wird empfohlen.",
    granted_note_wam: "Dieses Gerät erhält den Zugriff jetzt selbstständig.",

    no_action: "Keine Aktion — dieses Gerät kann nichts daran ändern",

    act_sign_in: "Anmelden…",
    act_sign_in_extend: "Zugriff verlängern…",
    act_create_grant: "Zugriff autorisieren…",
    act_create_grant_again: "Erneut autorisieren…",
    act_reinject: "Jetzt erneuern",
    act_cancel: "Abbrechen",
    act_drop_ticket: "Abmelden",
    act_sign_out_idp: "Von {idp} abmelden",
    act_give_up_grant: "Autorisierung entfernen…",
    act_enroll: "Windows einrichten…",
    act_reenroll: "Windows erneut einrichten…",
    act_unenroll: "{realm} vergessen…",
    act_restart_workstation: "Netzlaufwerke reparieren…",
    act_open_settings: "Einstellungen öffnen",
    act_open_log: "Protokollordner öffnen",

    err_broker_unreachable: "Netzwerk: {broker} hat nicht geantwortet. ({detail})",
    err_tls_untrusted: "TLS nicht vertrauenswürdig: Dieses Gerät kann nicht bestätigen, dass es wirklich mit {broker} spricht. Das muss eine Administration beheben.",
    err_broker_ambiguous_source: "Broker-Quelle fehlt: {broker} bedient mehrere Quellen ({sources}) und diese Adresse nennt keine davon. Die Broker-URL muss eine davon nennen; das muss eine Administration beheben.",
    err_not_admitted: "Realm-Zugriff verweigert: Ihr Konto ist in diesem Realm nicht zugelassen. Eine Administration muss den Zugriff gewähren. ({detail})",
    err_invalid_proof: "Anmeldung abgelehnt: {broker} hat Ihre Anmeldung nicht akzeptiert. ({detail})",
    err_rate_limited: "Broker ausgelastet: {broker} hat um Drosselung gebeten. NAS Access versucht es erneut.",
    err_server_unavailable: "Broker eingeschränkt: {broker} läuft, aber ein Dienst dahinter nicht. ({detail})",
    err_bad_request: "Broker-Protokoll: NAS Access hat eine Anfrage gesendet, die {broker} als fehlerhaft abgelehnt hat. ({detail})",
    err_broker_protocol: "Broker-Protokoll: {broker} hat auf eine Weise geantwortet, die NAS Access nicht versteht. ({detail})",
    err_idp_refused: "IdP abgelehnt: {issuer} hat die Anmeldung zurückgewiesen. ({detail})",
    err_sign_in: "Anmeldung fehlgeschlagen: {detail}",
    err_sign_in_timeout: "Zeitüberschreitung bei der Anmeldung: Die Browser-Anmeldung wurde nicht abgeschlossen.",
    err_silent_refresh: "Erneuerung fehlgeschlagen: {detail}",
    err_wam_empty: "WAM leer: Eine lautlose Anmeldung war nicht möglich — die Erneuerung braucht den Browser.",
    err_browser_required: "Die Erneuerung braucht eine Browser-Anmeldung.",
    err_internal: "NAS-Auth-Fehler: ein interner Fehler. ({detail})",
    err_grant_disabled: "Gerätegenehmigungen aus: Ihre Organisation erlaubt es hier nicht, die Browser-Anmeldung zu überspringen.",
    err_grant_key: "Schlüsselerstellung fehlgeschlagen: Dieses Gerät konnte den geschützten Schlüssel nicht erstellen. ({detail})",
    err_grant_failed: "Autorisierung fehlgeschlagen: Dieses Gerät wurde nicht autorisiert. ({detail})",
    err_grant_too_many: "Gerätegrenze erreicht: Ihr Konto hat bereits so viele autorisierte Geräte, wie Ihre Administration zulässt. Geben Sie eines auf, bevor Sie dieses Gerät hinzufügen. ({detail})",
    err_grant_not_allowed: "Geräteautorisierung verweigert: Ihr Konto darf die Browser-Anmeldung nicht überspringen. Das muss eine Administration freigeben. ({detail})",
    err_grant_not_delegate: "Kein Delegierter: Sie sind angemeldet, dürfen dieses Gerät aber nicht für dieses Konto einrichten. Jemand muss Sie zur Delegiertengruppe dieses Kontos hinzufügen. ({detail})",
    err_grant_reauthorize: "Delegiertes Konto: Die Einstellungen autorisieren den Zugriff für {target} — eine Anmeldung als jemand anderes ist nicht möglich.",
    err_elevation_failed: "Rechteerhöhung fehlgeschlagen: Der Administratorschritt konnte nicht gestartet werden. ({detail})",
    err_elevation_unavailable: "Rechteerhöhung nicht verfügbar: UAC ist auf diesem Gerät deaktiviert (EnableLUA=0), daher kann NAS Access keine Administratorrechte erhalten. Eine Administration muss dies aus einer erhöhten Eingabeaufforderung ausführen.",
    err_elevated_unconfirmed: "Nicht bestätigt: Der Administratorschritt endete, ohne ein Ergebnis zu melden.",

    fail_title_enroll: "Windows konnte nicht für {realm} eingerichtet werden",
    fail_title_repair: "Netzlaufwerke konnten nicht repariert werden",
    fail_title_unenroll: "{realm} konnte nicht entfernt werden",

    dlg_waiting: "Warten auf Berechtigung…",
    dlg_close: "Schließen",
    btn_cancel: "Abbrechen",

    dlg_repair_question: "Netzlaufwerke reparieren?",
    dlg_repair_body: "Dies startet den Arbeitsstationsdienst (LanmanWorkstation) neu. Jedes Netzlaufwerk und jeder freigegebene Ordner auf diesem Gerät wird getrennt, nicht nur die von {realm}, und Programme mit dort geöffneten Dateien können ungespeicherte Arbeit verlieren.",
    dlg_repair_dependents: "{services} wird dabei ebenfalls beendet und neu gestartet.",
    dlg_repair_save: "Speichern Sie Ihre Arbeit vorher.",
    dlg_repair_commit: "Trotzdem reparieren",
    dlg_repair_working: "Netzlaufwerke werden repariert…",
    repair_incomplete: "Die Reparatur wurde nicht sauber abgeschlossen. Das Protokoll enthält die Details.",
    dlg_repair_result: "Netzlaufwerke repariert. Andere Netzlaufwerke müssen eventuell neu geöffnet werden.",

    dlg_enroll_question: "Windows für {realm} einrichten?",
    dlg_enroll_body: "Diese Befehle werden als Administrator ausgeführt:",
    dlg_enroll_reboot: "Danach ist ein Neustart nötig: Windows liest einen Teil davon nur beim Start.",
    dlg_enroll_commit: "Windows einrichten",
    dlg_enroll_working: "Windows wird eingerichtet…",
    dlg_enroll_result: "Windows ist jetzt für {realm} eingerichtet. Zum Abschluss neu starten.",
    enroll_already: "Windows ist bereits für {realm} eingerichtet. Nichts zu tun.",
    enroll_incomplete: "Die Einrichtung wurde nicht sauber abgeschlossen. Das Protokoll enthält die Details.",
    enroll_discovery_failed: "Die Einrichtung konnte nicht vom Broker gelesen werden, daher wurde nichts geändert.",

    dlg_unenroll_question: "{realm} aus Windows entfernen?",
    dlg_unenroll_body: "Diese Registrierungsschlüssel werden als Administrator gelöscht:",
    dlg_unenroll_note: "Windows vertraut {realm} für Kerberos nicht mehr, bis es erneut eingerichtet wird.",
    dlg_unenroll_commit: "{realm} entfernen",
    dlg_unenroll_working: "{realm} wird aus Windows entfernt…",
    dlg_unenroll_result: "Windows kennt {realm} nicht mehr.",
    unenroll_already: "Windows ist nicht für {realm} eingerichtet. Nichts zu entfernen.",
    unenroll_incomplete: "Das Entfernen wurde nicht sauber abgeschlossen. Das Protokoll enthält die Details.",

    dlg_grant_off_question: "Autorisierung dieses Geräts entfernen?",
    dlg_grant_off_body: "Der Schlüssel im TPM dieses Geräts wird gelöscht und bei {broker} widerrufen. Das Löschen lässt sich nicht rückgängig machen — eine erneute Autorisierung erzeugt einen neuen Schlüssel.",
    dlg_grant_off_body_own: "Ihr Zugriff auf die Netzlaufwerke von {realm} ist davon nicht betroffen. Dieses Gerät meldet sich wieder so an wie vor der Autorisierung.",
    dlg_grant_off_body_delegated: "Dieses Gerät arbeitet als {target} und kann sich nicht als jemand anderes anmelden. Sein Zugriff auf die Netzlaufwerke von {realm} funktioniert noch {remaining} weiter und endet dann. Zum Fortsetzen muss sich hier jemand anmelden, der {target} autorisieren darf.",
    dlg_grant_off_commit: "Autorisierung entfernen",
    dlg_grant_off_working: "Autorisierung wird entfernt…",
    dlg_grant_off_result: "Autorisierung entfernt.",
    dlg_grant_off_result_sub: "Schlüssel auf diesem Gerät gelöscht · bei {broker} widerrufen",
    dlg_grant_off_result_stale: "Schlüssel auf diesem Gerät gelöscht · {broker} führt es weiterhin auf; eine Administration entfernt es mit `kbmanage device revoke`",
    dlg_grant_unsaved: "Dieses Gerät konnte seinen eigenen Eintrag nicht aktualisieren.",

    grant_confirm: "Dieses Gerät erreicht Ihre Netzlaufwerke ohne Browser-Anmeldung, für Ihr Konto auf diesem Gerät. Gültig: {days}.\r\n\r\nDer Schlüssel bleibt im TPM dieses Geräts und lässt sich nicht daraus kopieren. Ihre Administration kann ihn jederzeit widerrufen.",
    dlg_grant_commit: "Zugriff autorisieren",
    dlg_grant_working: "Gerät wird autorisiert…",
    grant_done: "Fertig. Dieses Gerät braucht {days} lang keine Browser-Anmeldung.",

    notify_ready_title: "Zugriff auf {realm} ist bereit",
    notify_ready_body: "{identity}. Der Zugriff gilt {duration}.",
    notify_expiring_title: "Zugriff auf {realm} endet in {duration}",
    notify_expiring_body: "Die Erneuerung hat nicht funktioniert. {action}, um den Zugriff zu behalten.",
    notify_stopped_title: "Zugriff auf {realm} beendet",
    notify_stopped_body: "{action}, um wieder Zugriff zu erhalten.",
    notify_grant_due_title: "Autorisierung läuft in {days} ab",
    notify_grant_due_body: "Dieses Gerät erreicht {realm} ohne Browser-Anmeldung. Autorisieren Sie den Zugriff vor {date} erneut, um das beizubehalten.",

    settings_title: "NAS Access — Einstellungen",
    tab_basic: "Allgemein",
    tab_advanced: "Erweitert",
    tab_about: "Info",
    settings_section_connection: "Verbindung",
    settings_broker_label: "Broker-URL",
    settings_broker_sub: "Server für die Verbindung — von Ihrem IT-Team",
    settings_broker_managed: "Von Ihrem IT-Team festgelegt — hier nicht änderbar.",
    settings_save: "Speichern",
    settings_gate: "Autorisierung und Windows-Einrichtung erscheinen, sobald die Konfiguration vollständig ist",
    settings_section_signin: "Anmeldung",
    settings_startup_label: "Beim Anmelden starten",
    settings_startup_sub: "Nach Ihrer Anmeldung automatisch anmelden.",
    settings_startup_managed: "Von Ihrem IT-Team für alle Benutzer dieses Computers aktiviert.",
    settings_wam_label: "Windows-Anmeldung verwenden, wenn möglich",
    settings_wam_sub: "Überspringt den Browser, wenn die Windows-eigene Anmeldung (WAM) ohne Nachfrage auskommt.",
    settings_section_authorization: "Autorisierung",
    settings_grant_state: "Zugriff autorisiert als {account}",
    settings_grant_for_label: "Dieses Gerät autorisieren für",
    settings_grant_for_sub: "Leer für Ihr eigenes Konto, oder ein anderes Konto, als das dieses Gerät arbeiten soll.",
    settings_section_windows: "Windows-Einrichtung",
    settings_enrolled: "Windows ist für {realm} eingerichtet.",
    settings_not_enrolled: "Windows ist nicht für {realm} eingerichtet.",
    settings_section_troubleshoot: "Fehlersuche",
    settings_troubleshoot_sub: "Ausführliche technische Aufzeichnungen darüber, was diese App getan hat — für den Fall, dass Ihnen jemand bei einem Problem hilft.",
    about_license: "Freie Software: Sie dürfen sie unter der GNU General Public License, Version 3 oder später, weitergeben und verändern. Dieses Programm wird ohne jede Gewährleistung bereitgestellt.",
    settings_ok: "OK",
    settings_cancel: "Abbrechen",
};
