use super::Strings;

pub(super) static EN: Strings = Strings {
    lang_tag: "en",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Open status",
    menu_settings: "Settings…",
    menu_help: "Help",
    menu_quit: "Quit NAS Access",

    cond_working: "Access OK",
    cond_flaky: "Renewal uncertain",
    cond_will_stop: "Access expiring",
    cond_stopped: "No access",
    cond_off: "Off",

    id_signed_in_as: "Signed in as {account}",
    id_working_as: "Working as {account}",

    access_ends_in: "Access ends in {duration}",
    grant_expires_in: "Authorization expires in {days}",
    dur_hours_minutes: "{h}h {m}m",
    dur_minutes: "{m}m",
    dur_under_a_minute: "under a minute",
    dur_one_day: "1 day",
    dur_days: "{d} days",

    blk_no_broker_url: "Broker URL not configured",
    blk_network_error: "Can't reach {broker}",
    blk_realm_unknown: "No settings from {broker}",
    blk_realm_not_registered: "Windows not set up for {realm}",
    blk_no_supply: "Needs a browser sign-in",
    blk_no_grant: "This device isn't authorized to work as {account}",
    blk_grant_refused: "Your organization refused this authorization",
    blk_refused: "Your account was refused",
    blk_ntlm_fallback: "Network drives stopped working (NTLM)",

    details_heading: "Kerberos details",
    meter_label: "Access valid for",
    d_realm: "Realm",
    d_source: "Source",
    d_ticket: "Ticket",
    d_ticket_value: "Renewable · ends {time}",
    d_ticket_value_norenew: "Ends {time}",
    d_supply: "Renews using",
    d_supply_grant: "this device's authorization",
    d_supply_wam: "your Windows account",
    d_supply_browser: "your browser sign-in",
    d_supply_none: "nothing — needs you",
    d_next: "Next attempt",

    err_sign_off_failed: "Sign-off failed: Windows refused to clear this realm's tickets. Any open shares may keep working.",
    signed_off_note: "Signed off. Network drives you already opened may keep working until you close them or restart this device.",
    granted_note: "This device can get access on its own now. Your browser is still signed in to {idp} — signing out there is recommended.",
    granted_note_wam: "This device can get access on its own now.",

    no_action: "No action — nothing this machine can do about it",

    act_sign_in: "Sign in…",
    act_sign_in_extend: "Extend access…",
    act_create_grant: "Authorize access…",
    act_create_grant_again: "Authorize again…",
    act_reinject: "Renew now",
    act_cancel: "Cancel",
    act_drop_ticket: "Sign off",
    act_sign_out_idp: "Sign out of {idp}",
    act_give_up_grant: "Remove authorization…",
    act_enroll: "Set up Windows…",
    act_reenroll: "Set up Windows again…",
    act_unenroll: "Forget {realm}…",
    act_restart_workstation: "Repair network drives…",
    act_open_settings: "Open settings",
    act_open_log: "Open log folder",

    err_broker_unreachable: "Network: {broker} didn't answer. ({detail})",
    err_tls_untrusted: "TLS untrusted: this device can't confirm it's really talking to {broker}. An administrator has to fix this.",
    err_broker_ambiguous_source: "Broker source missing: {broker} serves several sources ({sources}) and this address names none of them. The broker URL has to name one; an administrator has to fix this.",
    err_not_admitted: "Realm access denied: your account isn't allowed on this realm. An administrator has to grant access. ({detail})",
    err_invalid_proof: "Sign-in rejected: {broker} didn't accept your sign-in. ({detail})",
    err_rate_limited: "Broker busy: {broker} asked us to slow down. NAS Access will retry.",
    err_server_unavailable: "Broker degraded: {broker} is up, but a service behind it isn't. ({detail})",
    err_bad_request: "Broker protocol: NAS Access sent a request {broker} rejected as malformed. ({detail})",
    err_broker_protocol: "Broker protocol: {broker} answered in a way NAS Access doesn't understand. ({detail})",
    err_idp_refused: "IdP refused: {issuer} rejected the sign-in. ({detail})",
    err_sign_in: "Sign-in failed: {detail}",
    err_sign_in_timeout: "Sign-in timed out: the browser sign-in wasn't completed.",
    err_silent_refresh: "Renewal failed: {detail}",
    err_wam_empty: "WAM empty: silent sign-in wasn't possible — renewal needs the browser.",
    err_browser_required: "Renewal needs a browser sign-in.",
    err_internal: "NAS Access error: an internal fault. ({detail})",
    err_grant_disabled: "Device grants off: your organization doesn't allow skipping the browser sign-in here.",
    err_grant_key: "Key creation failed: this device couldn't create the protected key. ({detail})",
    err_grant_failed: "Authorization failed: this device wasn't authorized. ({detail})",
    err_grant_too_many: "Device cap reached: your account has as many authorized devices as your administrator allows. Give one up before adding this device. ({detail})",
    err_grant_not_allowed: "Device authorization denied: your account isn't allowed to skip the browser sign-in. An administrator has to grant that. ({detail})",
    err_grant_not_delegate: "Not a delegate: you're signed in, but not allowed to set this device up for that account. Someone has to add you to that account's delegate group. ({detail})",
    err_grant_reauthorize: "Delegated user: settings authorize access for {target} — can't sign in as anyone else.",
    err_elevation_failed: "Elevation failed: the administrator step couldn't start. ({detail})",
    err_elevation_unavailable: "Elevation unavailable: UAC is disabled on this device (EnableLUA=0), so NAS Access can't get administrator rights. An administrator has to run this from an elevated shell.",
    err_elevated_unconfirmed: "Couldn't confirm: the administrator step ended without reporting a result.",

    fail_title_enroll: "Couldn't set up Windows for {realm}",
    fail_title_repair: "Couldn't repair network drives",
    fail_title_unenroll: "Couldn't remove {realm}",

    dlg_waiting: "Waiting for permission…",
    dlg_close: "Close",
    btn_cancel: "Cancel",

    dlg_repair_question: "Repair network drives?",
    dlg_repair_body: "This restarts the Workstation service (LanmanWorkstation). Every network drive and shared folder on this device disconnects, not only {realm}'s, and programs with files open on them may lose unsaved work.",
    dlg_repair_dependents: "{services} stops and starts again with it.",
    dlg_repair_save: "Save your work first.",
    dlg_repair_commit: "Repair anyway",
    dlg_repair_working: "Repairing network drives…",
    repair_incomplete: "The repair didn't finish cleanly. The log has the details.",
    dlg_repair_result: "Network drives repaired. Other network drives may need reopening.",

    dlg_enroll_question: "Set up Windows for {realm}?",
    dlg_enroll_body: "These commands run as administrator:",
    dlg_enroll_reboot: "A restart is needed afterwards: Windows only reads part of this at boot.",
    dlg_enroll_commit: "Set up Windows",
    dlg_enroll_working: "Setting up Windows…",
    dlg_enroll_result: "Windows is now set up for {realm}. Restart to finish.",
    enroll_already: "Windows is already set up for {realm}. Nothing to do.",
    enroll_incomplete: "Setup didn't finish cleanly. The log has the details.",
    enroll_discovery_failed: "Couldn't read the setup from the broker, so nothing was changed.",

    dlg_unenroll_question: "Remove {realm} from Windows?",
    dlg_unenroll_body: "These registry keys are deleted as administrator:",
    dlg_unenroll_note: "Windows will no longer trust {realm} for Kerberos until it is set up again.",
    dlg_unenroll_commit: "Remove {realm}",
    dlg_unenroll_working: "Removing {realm} from Windows…",
    dlg_unenroll_result: "Windows no longer knows about {realm}.",
    unenroll_already: "Windows is not set up for {realm}. Nothing to remove.",
    unenroll_incomplete: "Removal didn't finish cleanly. The log has the details.",

    dlg_grant_off_question: "Remove this device's authorization?",
    dlg_grant_off_body: "The key in this device's TPM is deleted and revoked at {broker}. Deleting it can't be undone — authorizing again creates a new key.",
    dlg_grant_off_body_own: "Your access to {realm} network drives is not affected. This device signs in the way it did before it was authorized.",
    dlg_grant_off_body_delegated: "This device works as {target} and can't sign in as anyone else. Its access to {realm} network drives keeps working until it expires in {remaining}, and then stops. To start it again, someone allowed to authorize {target} has to sign in here.",
    dlg_grant_off_commit: "Remove authorization",
    dlg_grant_off_working: "Removing authorization…",
    dlg_grant_off_result: "Authorization removed.",
    dlg_grant_off_result_sub: "Key deleted on this device · revoked at {broker}",
    dlg_grant_off_result_stale: "Key deleted on this device · {broker} still lists it, and an administrator clears it with `kbmanage device revoke`",
    dlg_grant_unsaved: "This device couldn't update its own record.",

    grant_confirm: "This device can reach your network drives without a browser sign-in, for your account on this device. Valid for {days}.\r\n\r\nThe key stays in this device's TPM and cannot be copied off it. Your administrator can revoke it at any time.",
    dlg_grant_commit: "Authorize access",
    dlg_grant_working: "Authorizing this device…",
    grant_done: "Done. This device won't need a browser sign-in for {days}.",

    notify_ready_title: "{realm} access is ready",
    notify_ready_body: "{identity}. Access lasts for {duration}.",
    notify_expiring_title: "Access to {realm} ends in {duration}",
    notify_expiring_body: "Renewal hasn't worked. {action} to keep access.",
    notify_stopped_title: "Access to {realm} ended",
    notify_stopped_body: "{action} to get access again.",
    notify_grant_due_title: "Authorization expires in {days}",
    notify_grant_due_body: "This device reaches {realm} without a browser sign-in. Authorize access again before {date} to keep it.",

    settings_title: "NAS Access — Settings",
    tab_basic: "Basic",
    tab_advanced: "Advanced",
    tab_about: "About",
    settings_section_connection: "Connection",
    settings_broker_label: "Broker URL",
    settings_broker_sub: "Server to connect — from your IT team",
    settings_broker_managed: "Set by your IT team — this can't be changed here.",
    settings_save: "Save",
    settings_gate: "Authorization and Windows setup appear once configuration is complete",
    settings_section_signin: "Sign-in",
    settings_startup_label: "Start at login",
    settings_startup_sub: "Sign in automatically after you log in.",
    settings_startup_managed: "Turned on by your IT team for everyone on this computer.",
    settings_wam_label: "Use Windows sign-in when possible",
    settings_wam_sub: "Skips the browser when Windows' own sign-in (WAM) needs no prompt.",
    settings_section_authorization: "Authorization",
    settings_grant_state: "Access authorized as {account}",
    settings_grant_for_label: "Authorize this device for",
    settings_grant_for_sub: "Empty for your own account, or another account this device should work as.",
    settings_section_windows: "Windows setup",
    settings_enrolled: "Windows is set up for {realm}.",
    settings_not_enrolled: "Windows is not set up for {realm}.",
    settings_section_troubleshoot: "Troubleshoot",
    settings_troubleshoot_sub: "Detailed technical records of what this app did, for when someone is helping you sort out a problem.",
    about_license: "Free software: you can redistribute it and modify it under the GNU General Public License, version 3 or later. This program comes with absolutely no warranty.",
    settings_ok: "OK",
    settings_cancel: "Cancel",
};
