use super::Strings;

pub(super) static ES: Strings = Strings {
    lang_tag: "es",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Abrir estado",
    menu_settings: "Configuración…",
    menu_help: "Ayuda",
    menu_quit: "Salir de NAS Access",

    cond_working: "Acceso correcto",
    cond_flaky: "Renovación incierta",
    cond_will_stop: "Acceso por vencer",
    cond_stopped: "Sin acceso",
    cond_off: "Desactivado",

    id_signed_in_as: "Sesión iniciada como {account}",
    id_working_as: "Funciona como {account}",

    access_ends_in: "El acceso termina en {duration}",
    grant_expires_in: "La autorización vence en {days}",
    dur_hours_minutes: "{h} h {m} min",
    dur_minutes: "{m} min",
    dur_under_a_minute: "menos de un minuto",
    dur_one_day: "1 día",
    dur_days: "{d} días",

    blk_no_broker_url: "URL del bróker sin configurar",
    blk_network_error: "No se puede contactar con {broker}",
    blk_realm_unknown: "No hay configuración de {broker}",
    blk_realm_not_registered: "Windows no está configurado para {realm}",
    blk_no_supply: "Requiere iniciar sesión en el navegador",
    blk_no_grant: "Este dispositivo no está autorizado a funcionar como {account}",
    blk_grant_refused: "Tu organización rechazó esta autorización",
    blk_refused: "Tu cuenta fue rechazada",
    blk_ntlm_fallback: "Las unidades de red dejaron de funcionar (NTLM)",

    details_heading: "Detalles de Kerberos",
    meter_label: "Acceso válido durante",
    d_realm: "Reino",
    d_source: "Origen",
    d_ticket: "Ticket",
    d_ticket_value: "Renovable · finaliza a las {time}",
    d_ticket_value_norenew: "Finaliza a las {time}",
    d_supply: "Se renueva con",
    d_supply_grant: "la autorización de este dispositivo",
    d_supply_wam: "tu cuenta de Windows",
    d_supply_browser: "tu sesión del navegador",
    d_supply_none: "nada: te necesita a ti",
    d_next: "Próximo intento",

    err_sign_off_failed: "Error al cerrar sesión: Windows se negó a borrar los tickets de este dominio. Los recursos abiertos pueden seguir funcionando.",
    signed_off_note: "Sesión cerrada. Las unidades de red que ya abriste pueden seguir funcionando hasta que las cierres o reinicies este dispositivo.",
    granted_note: "Este dispositivo ya puede obtener acceso por su cuenta. Tu navegador sigue con la sesión iniciada en {idp}: se recomienda cerrarla.",
    granted_note_wam: "Este dispositivo ya puede obtener acceso por su cuenta. T",

    no_action: "Sin acciones: este dispositivo no puede hacer nada al respecto",

    act_sign_in: "Iniciar sesión…",
    act_sign_in_extend: "Ampliar el acceso…",
    act_create_grant: "Autorizar el acceso…",
    act_create_grant_again: "Autorizar de nuevo…",
    act_reinject: "Renovar ahora",
    act_cancel: "Cancelar",
    act_drop_ticket: "Cerrar el acceso",
    act_sign_out_idp: "Cerrar sesión en {idp}",
    act_give_up_grant: "Quitar la autorización…",
    act_enroll: "Configurar Windows…",
    act_reenroll: "Configurar Windows otra vez…",
    act_unenroll: "Olvidar {realm}…",
    act_restart_workstation: "Reparar las unidades de red…",
    act_open_settings: "Abrir la configuración",
    act_open_log: "Abrir la carpeta del registro",

    err_broker_unreachable: "Red: {broker} no respondió. ({detail})",
    err_tls_untrusted: "TLS no confiable: este dispositivo no puede confirmar que realmente esté hablando con {broker}. Un administrador tiene que arreglarlo.",
    err_broker_ambiguous_source: "Fuente del bróker sin indicar: {broker} atiende varias fuentes ({sources}) y esta dirección no nombra ninguna. La URL del bróker tiene que nombrar una; un administrador tiene que arreglarlo.",
    err_not_admitted: "Acceso al reino denegado: tu cuenta no está admitida en este reino. Un administrador tiene que concederte el acceso. ({detail})",
    err_invalid_proof: "Inicio de sesión rechazado: {broker} no aceptó tu inicio de sesión. ({detail})",
    err_rate_limited: "Bróker ocupado: {broker} pidió que redujéramos el ritmo. NAS Access lo intentará de nuevo.",
    err_server_unavailable: "Bróker degradado: {broker} está activo, pero un servicio detrás de él no lo está. ({detail})",
    err_bad_request: "Protocolo del bróker: NAS Access envió una solicitud que {broker} rechazó por estar mal formada. ({detail})",
    err_broker_protocol: "Protocolo del bróker: {broker} respondió de una forma que NAS Access no entiende. ({detail})",
    err_idp_refused: "IdP rechazó: {issuer} denegó el inicio de sesión. ({detail})",
    err_sign_in: "Error de inicio de sesión: {detail}",
    err_sign_in_timeout: "Tiempo de inicio de sesión agotado: no se completó el inicio de sesión en el navegador.",
    err_silent_refresh: "Error de renovación: {detail}",
    err_wam_empty: "WAM vacío: no fue posible iniciar sesión en silencio; la renovación necesita el navegador.",
    err_browser_required: "La renovación necesita iniciar sesión en el navegador.",
    err_internal: "Error de NAS Access: un fallo interno. ({detail})",
    err_grant_disabled: "Concesiones de dispositivo desactivadas: tu organización no permite omitir aquí el inicio de sesión del navegador.",
    err_grant_key: "Error al crear la clave: este dispositivo no pudo crear la clave protegida. ({detail})",
    err_grant_failed: "Error de autorización: este dispositivo no fue autorizado. ({detail})",
    err_grant_too_many: "Límite de dispositivos alcanzado: tu cuenta ya tiene tantos dispositivos autorizados como permite tu administrador. Quita uno antes de añadir este dispositivo. ({detail})",
    err_grant_not_allowed: "Autorización de dispositivo denegada: tu cuenta no puede omitir el inicio de sesión del navegador. Un administrador tiene que concederlo. ({detail})",
    err_grant_not_delegate: "No eres delegado: has iniciado sesión, pero no puedes configurar este dispositivo para esa cuenta. Alguien debe añadirte al grupo de delegados de esa cuenta. ({detail})",
    err_grant_reauthorize: "Usuario delegado: la configuración autoriza el acceso para {target}; no se puede iniciar sesión como nadie más.",
    err_elevation_failed: "Error de elevación: no se pudo iniciar el paso de administrador. ({detail})",
    err_elevation_unavailable: "Elevación no disponible: el UAC está desactivado en este dispositivo (EnableLUA=0), así que NAS Access no puede obtener permisos de administrador. Un administrador tiene que ejecutar esto desde un símbolo del sistema elevado.",
    err_elevated_unconfirmed: "Sin confirmación: el paso de administrador terminó sin informar de un resultado.",

    fail_title_enroll: "No se pudo configurar Windows para {realm}",
    fail_title_repair: "No se pudieron reparar las unidades de red",
    fail_title_unenroll: "No se pudo quitar {realm}",

    dlg_waiting: "Esperando permiso…",
    dlg_close: "Cerrar",
    btn_cancel: "Cancelar",

    dlg_repair_question: "¿Reparar las unidades de red?",
    dlg_repair_body: "Esto reinicia el servicio Estación de trabajo (LanmanWorkstation). Todas las unidades de red y carpetas compartidas de este dispositivo se desconectan, no solo las de {realm}, y los programas con archivos abiertos en ellas pueden perder trabajo sin guardar.",
    dlg_repair_dependents: "{services} se detiene y se vuelve a iniciar con él.",
    dlg_repair_save: "Guarda tu trabajo primero.",
    dlg_repair_commit: "Reparar de todos modos",
    dlg_repair_working: "Reparando las unidades de red…",
    repair_incomplete: "La reparación no terminó limpiamente. El registro tiene los detalles.",
    dlg_repair_result: "Unidades de red reparadas. Puede que haya que volver a abrir otras unidades de red.",

    dlg_enroll_question: "¿Configurar Windows para {realm}?",
    dlg_enroll_body: "Estos comandos se ejecutan como administrador:",
    dlg_enroll_reboot: "Después hace falta reiniciar: Windows solo lee parte de esto al arrancar.",
    dlg_enroll_commit: "Configurar Windows",
    dlg_enroll_working: "Configurando Windows…",
    dlg_enroll_result: "Windows ya está configurado para {realm}. Reinicia para terminar.",
    enroll_already: "Windows ya está configurado para {realm}. No hay nada que hacer.",
    enroll_incomplete: "La configuración no terminó limpiamente. El registro tiene los detalles.",
    enroll_discovery_failed: "No se pudo leer la configuración del bróker, así que no se cambió nada.",

    dlg_unenroll_question: "¿Quitar {realm} de Windows?",
    dlg_unenroll_body: "Estas claves del registro se eliminan como administrador:",
    dlg_unenroll_note: "Windows dejará de confiar en {realm} para Kerberos hasta que se vuelva a configurar.",
    dlg_unenroll_commit: "Quitar {realm}",
    dlg_unenroll_working: "Quitando {realm} de Windows…",
    dlg_unenroll_result: "Windows ya no conoce {realm}.",
    unenroll_already: "Windows no está configurado para {realm}. No hay nada que quitar.",
    unenroll_incomplete: "La eliminación no terminó limpiamente. El registro tiene los detalles.",

    dlg_grant_off_question: "¿Quitar la autorización de este dispositivo?",
    dlg_grant_off_body: "La clave del TPM de este dispositivo se elimina y se revoca en {broker}. Eliminarla no se puede deshacer: autorizar de nuevo crea una clave nueva.",
    dlg_grant_off_body_own: "Tu acceso a las unidades de red de {realm} no se ve afectado. Este dispositivo inicia sesión como lo hacía antes de ser autorizado.",
    dlg_grant_off_body_delegated: "Este dispositivo funciona como {target} y no puede iniciar sesión como nadie más. Su acceso a las unidades de red de {realm} sigue funcionando hasta que venza dentro de {remaining}, y entonces se detiene. Para volver a activarlo, alguien con permiso para autorizar a {target} tiene que iniciar sesión aquí.",
    dlg_grant_off_commit: "Quitar la autorización",
    dlg_grant_off_working: "Quitando la autorización…",
    dlg_grant_off_result: "Autorización eliminada.",
    dlg_grant_off_result_sub: "Clave eliminada en este dispositivo · revocada en {broker}",
    dlg_grant_off_result_stale: "Clave eliminada en este dispositivo · {broker} todavía lo tiene en la lista, y un administrador lo quita con `kbmanage device revoke`",
    dlg_grant_unsaved: "Este dispositivo no pudo actualizar su propio registro.",

    grant_confirm: "Este dispositivo puede llegar a tus unidades de red sin iniciar sesión en el navegador, para tu cuenta en este dispositivo. Validez: {days}.\r\n\r\nLa clave permanece en el TPM de este dispositivo y no se puede copiar fuera de él. Tu administrador puede revocarla en cualquier momento.",
    dlg_grant_commit: "Autorizar el acceso",
    dlg_grant_working: "Autorizando este dispositivo…",
    grant_done: "Listo. Este dispositivo no necesitará iniciar sesión en el navegador durante {days}.",

    notify_ready_title: "El acceso a {realm} está listo",
    notify_ready_body: "{identity}. El acceso dura {duration}.",
    notify_expiring_title: "El acceso a {realm} termina en {duration}",
    notify_expiring_body: "La renovación no ha funcionado. {action} para conservar el acceso.",
    notify_stopped_title: "El acceso a {realm} terminó",
    notify_stopped_body: "{action} para volver a tener acceso.",
    notify_grant_due_title: "La autorización vence en {days}",
    notify_grant_due_body: "Este dispositivo llega a {realm} sin iniciar sesión en el navegador. Autoriza el acceso de nuevo antes del {date} para conservarlo.",

    settings_title: "NAS Access — Configuración",
    tab_basic: "Básico",
    tab_advanced: "Avanzado",
    tab_about: "Acerca de",
    settings_section_connection: "Conexión",
    settings_broker_label: "URL del bróker",
    settings_broker_sub: "Servidor al que conectarse — de tu equipo de TI",
    settings_broker_managed: "Establecida por tu equipo de TI — no se puede cambiar aquí.",
    settings_save: "Guardar",
    settings_gate: "La autorización y la configuración de Windows aparecen cuando la configuración está completa",
    settings_section_signin: "Inicio de sesión",
    settings_startup_label: "Abrir al iniciar sesión",
    settings_startup_sub: "Inicia sesión automáticamente después de acceder al equipo.",
    settings_startup_managed: "Activado por tu equipo de TI para todos los que usan este equipo.",
    settings_wam_label: "Usar el inicio de sesión de Windows cuando sea posible",
    settings_wam_sub: "Omite el navegador cuando el inicio de sesión propio de Windows (WAM) no necesita preguntar nada.",
    settings_section_authorization: "Autorización",
    settings_grant_state: "Acceso autorizado como {account}",
    settings_grant_for_label: "Autorizar este dispositivo para",
    settings_grant_for_sub: "Vacío para tu propia cuenta, u otra cuenta como la que deba funcionar este dispositivo.",
    settings_section_windows: "Configuración de Windows",
    settings_enrolled: "Windows está configurado para {realm}.",
    settings_not_enrolled: "Windows no está configurado para {realm}.",
    settings_section_troubleshoot: "Solución de problemas",
    settings_troubleshoot_sub: "Registros técnicos detallados de lo que hizo esta aplicación, para cuando alguien te esté ayudando a resolver un problema.",
    about_license: "Software libre: puede redistribuirlo y modificarlo bajo la Licencia Pública General de GNU, versión 3 o posterior. Este programa se ofrece sin ninguna garantía.",
    settings_ok: "Aceptar",
    settings_cancel: "Cancelar",
};
