use super::Strings;

pub(super) static FI: Strings = Strings {
    lang_tag: "fi",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Avaa tila",
    menu_settings: "Asetukset…",
    menu_help: "Ohje",
    menu_quit: "Lopeta NAS Access",

    cond_working: "Käyttöoikeus kunnossa",
    cond_flaky: "Uusiminen epävarmaa",
    cond_will_stop: "Käyttöoikeus päättymässä",
    cond_stopped: "Ei käyttöoikeutta",
    cond_off: "Pois",

    id_signed_in_as: "Kirjautuneena tunnuksella {account}",
    id_working_as: "Toimii tunnuksella {account}",

    access_ends_in: "Käyttöoikeus päättyy {duration} kuluttua",
    grant_expires_in: "Valtuutus vanhenee {days} kuluttua",
    dur_hours_minutes: "{h} t {m} min",
    dur_minutes: "{m} min",
    dur_under_a_minute: "alle minuutti",
    dur_one_day: "1 päivä",
    dur_days: "{d} päivää",

    blk_no_broker_url: "Välityspalvelimen URL-osoitetta ei ole määritetty",
    blk_network_error: "Osoitteeseen {broker} ei saada yhteyttä",
    blk_realm_unknown: "Palvelimelta {broker} ei ole asetuksia",
    blk_realm_not_registered: "Windowsia ei ole määritetty alueelle {realm}",
    blk_no_supply: "Vaatii selainkirjautumisen",
    blk_no_grant: "Tätä laitetta ei ole valtuutettu toimimaan tunnuksella {account}",
    blk_grant_refused: "Organisaatiosi hylkäsi tämän valtuutuksen",
    blk_refused: "Tilisi hylättiin",
    blk_ntlm_fallback: "Verkkoasemat lakkasivat toimimasta (NTLM)",

    details_heading: "Kerberos-tiedot",
    meter_label: "Käyttöoikeus voimassa",
    d_realm: "Alue",
    d_source: "Lähde",
    d_ticket: "Lippu",
    d_ticket_value: "Uusittavissa · päättyy klo {time}",
    d_ticket_value_norenew: "Päättyy klo {time}",
    d_supply: "Uusitaan tavalla",
    d_supply_grant: "tämän laitteen valtuutus",
    d_supply_wam: "Windows-tilisi",
    d_supply_browser: "selainkirjautumisesi",
    d_supply_none: "ei mikään — tarvitsee sinua",
    d_next: "Seuraava yritys",

    err_sign_off_failed: "Uloskirjautuminen epäonnistui: Windows kieltäytyi poistamasta tämän realmin lippuja. Avoimet jaot voivat yhä toimia.",
    signed_off_note: "Kirjauduttu ulos. Jo avaamasi verkkoasemat voivat toimia edelleen, kunnes suljet ne tai käynnistät tämän laitteen uudelleen.",
    granted_note: "Tämä laite saa käyttöoikeuden nyt itsenäisesti. Selaimesi on yhä kirjautuneena palveluun {idp} — uloskirjautumista suositellaan.",
    granted_note_wam: "Tämä laite saa käyttöoikeuden nyt itsenäisesti. Se",

    no_action: "Ei toimintoa — tämä laite ei voi tehdä asialle mitään",

    act_sign_in: "Kirjaudu sisään…",
    act_sign_in_extend: "Jatka käyttöoikeutta…",
    act_create_grant: "Valtuuta käyttöoikeus…",
    act_create_grant_again: "Valtuuta uudelleen…",
    act_reinject: "Uusi nyt",
    act_cancel: "Peruuta",
    act_drop_ticket: "Kirjaudu pois",
    act_sign_out_idp: "Kirjaudu ulos palvelusta {idp}",
    act_give_up_grant: "Poista valtuutus…",
    act_enroll: "Määritä Windows…",
    act_reenroll: "Määritä Windows uudelleen…",
    act_unenroll: "Unohda {realm}…",
    act_restart_workstation: "Korjaa verkkoasemat…",
    act_open_settings: "Avaa asetukset",
    act_open_log: "Avaa lokikansio",

    err_broker_unreachable: "Verkko: {broker} ei vastannut. ({detail})",
    err_tls_untrusted: "TLS ei luotettu: tämä laite ei voi varmistaa, että se todella keskustelee palvelimen {broker} kanssa. Järjestelmänvalvojan on korjattava tämä.",
    err_broker_ambiguous_source: "Lähde nimeämättä: {broker} palvelee useita lähteitä ({sources}) eikä tämä osoite nimeä niistä yhtään. Välityspalvelimen osoitteen on nimettävä yksi; järjestelmänvalvojan on korjattava tämä.",
    err_not_admitted: "Alueen käyttö evätty: tilisi ei ole sallittu tällä alueella. Järjestelmänvalvojan on myönnettävä käyttöoikeus. ({detail})",
    err_invalid_proof: "Kirjautuminen hylätty: {broker} ei hyväksynyt kirjautumistasi. ({detail})",
    err_rate_limited: "Välityspalvelin ruuhkautunut: {broker} pyysi hidastamaan. NAS Access yrittää uudelleen.",
    err_server_unavailable: "Välityspalvelin osittain toimintakyvytön: {broker} on käynnissä, mutta jokin sen takana oleva palvelu ei ole. ({detail})",
    err_bad_request: "Välityspalvelinprotokolla: NAS Access lähetti pyynnön, jonka {broker} hylkäsi virheellisenä. ({detail})",
    err_broker_protocol: "Välityspalvelinprotokolla: {broker} vastasi tavalla, jota NAS Access ei ymmärrä. ({detail})",
    err_idp_refused: "Käyttäjätunnistuspalvelu hylkäsi: {issuer} torjui kirjautumisen. ({detail})",
    err_sign_in: "Kirjautuminen epäonnistui: {detail}",
    err_sign_in_timeout: "Kirjautuminen aikakatkaistiin: selainkirjautumista ei viety loppuun.",
    err_silent_refresh: "Uusiminen epäonnistui: {detail}",
    err_wam_empty: "WAM tyhjä: hiljainen kirjautuminen ei onnistunut — uusiminen vaatii selaimen.",
    err_browser_required: "Uusiminen vaatii selainkirjautumisen.",
    err_internal: "NAS Access -virhe: sisäinen vika. ({detail})",
    err_grant_disabled: "Laitevaltuutukset pois käytöstä: organisaatiosi ei salli selainkirjautumisen ohittamista täällä.",
    err_grant_key: "Avaimen luonti epäonnistui: tämä laite ei voinut luoda suojattua avainta. ({detail})",
    err_grant_failed: "Valtuutus epäonnistui: tätä laitetta ei valtuutettu. ({detail})",
    err_grant_too_many: "Laiteraja saavutettu: tililläsi on jo niin monta valtuutettua laitetta kuin järjestelmänvalvoja sallii. Luovu yhdestä ennen tämän laitteen lisäämistä. ({detail})",
    err_grant_not_allowed: "Laitevaltuutus evätty: tililläsi ei ole oikeutta ohittaa selainkirjautumista. Järjestelmänvalvojan on myönnettävä se. ({detail})",
    err_grant_not_delegate: "Ei valtuutettu: olet kirjautunut sisään, mutta sinulla ei ole oikeutta määrittää tätä laitetta kyseiselle tilille. Sinut on lisättävä kyseisen tilin valtuutettujen ryhmään. ({detail})",
    err_grant_reauthorize: "Valtuutettu käyttäjä: asetukset valtuuttavat käyttöoikeuden tunnukselle {target} — kukaan muu ei voi kirjautua sisään.",
    err_elevation_failed: "Oikeuksien korotus epäonnistui: järjestelmänvalvojan vaihetta ei voitu käynnistää. ({detail})",
    err_elevation_unavailable: "Oikeuksien korotus ei käytettävissä: käyttäjätilien valvonta (UAC) on poistettu käytöstä tässä laitteessa (EnableLUA=0), joten NAS Access ei voi saada järjestelmänvalvojan oikeuksia. Järjestelmänvalvojan on suoritettava tämä korotetusta komentokehotteesta.",
    err_elevated_unconfirmed: "Vahvistus puuttuu: järjestelmänvalvojan vaihe päättyi ilmoittamatta tulosta.",

    fail_title_enroll: "Windowsia ei voitu määrittää alueelle {realm}",
    fail_title_repair: "Verkkoasemia ei voitu korjata",
    fail_title_unenroll: "Aluetta {realm} ei voitu poistaa",

    dlg_waiting: "Odotetaan lupaa…",
    dlg_close: "Sulje",
    btn_cancel: "Peruuta",

    dlg_repair_question: "Korjataanko verkkoasemat?",
    dlg_repair_body: "Tämä käynnistää Workstation-palvelun (LanmanWorkstation) uudelleen. Kaikki tämän laitteen verkkoasemat ja jaetut kansiot katkeavat, eivät vain alueen {realm} omat, ja ohjelmat, joilla on niissä avoimia tiedostoja, voivat menettää tallentamatonta työtä.",
    dlg_repair_dependents: "{services} pysäytetään ja käynnistetään sen mukana.",
    dlg_repair_save: "Tallenna työsi ensin.",
    dlg_repair_commit: "Korjaa silti",
    dlg_repair_working: "Korjataan verkkoasemia…",
    repair_incomplete: "Korjaus ei päättynyt siististi. Loki sisältää tiedot.",
    dlg_repair_result: "Verkkoasemat korjattu. Muut verkkoasemat voi olla tarpeen avata uudelleen.",

    dlg_enroll_question: "Määritetäänkö Windows alueelle {realm}?",
    dlg_enroll_body: "Nämä komennot suoritetaan järjestelmänvalvojana:",
    dlg_enroll_reboot: "Jälkeenpäin tarvitaan uudelleenkäynnistys: Windows lukee osan tästä vain käynnistyksen yhteydessä.",
    dlg_enroll_commit: "Määritä Windows",
    dlg_enroll_working: "Määritetään Windowsia…",
    dlg_enroll_result: "Windows on nyt määritetty alueelle {realm}. Viimeistele käynnistämällä uudelleen.",
    enroll_already: "Windows on jo määritetty alueelle {realm}. Ei tehtävää.",
    enroll_incomplete: "Määritys ei päättynyt siististi. Loki sisältää tiedot.",
    enroll_discovery_failed: "Asetuksia ei voitu lukea välityspalvelimelta, joten mitään ei muutettu.",

    dlg_unenroll_question: "Poistetaanko {realm} Windowsista?",
    dlg_unenroll_body: "Nämä rekisteriavaimet poistetaan järjestelmänvalvojana:",
    dlg_unenroll_note: "Windows ei enää luota alueeseen {realm} Kerberosissa, ennen kuin se määritetään uudelleen.",
    dlg_unenroll_commit: "Poista {realm}",
    dlg_unenroll_working: "Poistetaan {realm} Windowsista…",
    dlg_unenroll_result: "Windows ei enää tunne aluetta {realm}.",
    unenroll_already: "Windowsia ei ole määritetty alueelle {realm}. Ei poistettavaa.",
    unenroll_incomplete: "Poisto ei päättynyt siististi. Loki sisältää tiedot.",

    dlg_grant_off_question: "Poistetaanko tämän laitteen valtuutus?",
    dlg_grant_off_body: "Tämän laitteen TPM-piirissä oleva avain poistetaan ja peruutetaan palvelimella {broker}. Poistoa ei voi kumota — uusi valtuutus luo uuden avaimen.",
    dlg_grant_off_body_own: "Käyttöoikeutesi alueen {realm} verkkoasemiin ei muutu. Tämä laite kirjautuu sisään samalla tavalla kuin ennen valtuutusta.",
    dlg_grant_off_body_delegated: "Tämä laite toimii tunnuksella {target} eikä voi kirjautua sisään kenenkään muun nimissä. Sen käyttöoikeus alueen {realm} verkkoasemiin toimii vielä {remaining} ja päättyy sitten. Käynnistääkseen sen uudelleen jonkun, jolla on oikeus valtuuttaa {target}, on kirjauduttava täällä sisään.",
    dlg_grant_off_commit: "Poista valtuutus",
    dlg_grant_off_working: "Poistetaan valtuutusta…",
    dlg_grant_off_result: "Valtuutus poistettu.",
    dlg_grant_off_result_sub: "Avain poistettu tästä laitteesta · peruutettu palvelimella {broker}",
    dlg_grant_off_result_stale: "Avain poistettu tästä laitteesta · {broker} luetteloi sen yhä, ja järjestelmänvalvoja poistaa sen komennolla `kbmanage device revoke`",
    dlg_grant_unsaved: "Tämä laite ei voinut päivittää omaa tietuettaan.",

    grant_confirm: "Tämä laite pääsee verkkoasemiisi ilman selainkirjautumista, tällä laitteella olevalla tililläsi. Voimassa {days}.\r\n\r\nAvain pysyy tämän laitteen TPM-piirissä, eikä sitä voi kopioida pois. Järjestelmänvalvoja voi peruuttaa sen milloin tahansa.",
    dlg_grant_commit: "Valtuuta käyttöoikeus",
    dlg_grant_working: "Valtuutetaan tätä laitetta…",
    grant_done: "Valmis. Tämä laite ei tarvitse selainkirjautumista {days} aikana.",

    notify_ready_title: "Alueen {realm} käyttöoikeus on valmis",
    notify_ready_body: "{identity}. Käyttöoikeus kestää {duration}.",
    notify_expiring_title: "Alueen {realm} käyttöoikeus päättyy {duration} kuluttua",
    notify_expiring_body: "Uusiminen ei ole onnistunut. {action} säilyttääksesi käyttöoikeuden.",
    notify_stopped_title: "Alueen {realm} käyttöoikeus päättyi",
    notify_stopped_body: "{action} saadaksesi käyttöoikeuden uudelleen.",
    notify_grant_due_title: "Valtuutus vanhenee {days} kuluttua",
    notify_grant_due_body: "Tämä laite tavoittaa alueen {realm} ilman selainkirjautumista. Valtuuta käyttöoikeus uudelleen ennen {date} säilyttääksesi sen.",

    settings_title: "NAS Access — Asetukset",
    tab_basic: "Perusasetukset",
    tab_advanced: "Lisäasetukset",
    tab_about: "Tietoja",
    settings_section_connection: "Yhteys",
    settings_broker_label: "Välityspalvelimen URL-osoite",
    settings_broker_sub: "Palvelin, johon yhdistetään — IT-tuestasi",
    settings_broker_managed: "IT-tukesi asettama — tätä ei voi muuttaa täällä.",
    settings_save: "Tallenna",
    settings_gate: "Valtuutus ja Windowsin määritys tulevat näkyviin, kun asetukset ovat valmiit",
    settings_section_signin: "Kirjautuminen",
    settings_startup_label: "Käynnistä kirjautumisen yhteydessä",
    settings_startup_sub: "Kirjaa sisään automaattisesti sisäänkirjautumisesi jälkeen.",
    settings_startup_managed: "IT-tukesi on ottanut tämän käyttöön kaikille tämän tietokoneen käyttäjille.",
    settings_wam_label: "Käytä Windows-kirjautumista, kun se on mahdollista",
    settings_wam_sub: "Ohittaa selaimen, kun Windowsin oma kirjautuminen (WAM) ei vaadi kysymyksiä.",
    settings_section_authorization: "Valtuutus",
    settings_grant_state: "Käyttöoikeus valtuutettu tunnukselle {account}",
    settings_grant_for_label: "Valtuuta tämä laite tunnukselle",
    settings_grant_for_sub: "Tyhjä omalle tilillesi, tai toinen tili, jona tämän laitteen tulisi toimia.",
    settings_section_windows: "Windowsin määritys",
    settings_enrolled: "Windows on määritetty alueelle {realm}.",
    settings_not_enrolled: "Windowsia ei ole määritetty alueelle {realm}.",
    settings_section_troubleshoot: "Vianmääritys",
    settings_troubleshoot_sub: "Yksityiskohtaiset tekniset merkinnät siitä, mitä tämä sovellus teki — siltä varalta, että joku auttaa sinua ongelman selvittämisessä.",
    about_license: "Vapaa ohjelmisto: saat levittää ja muokata sitä GNU General Public License -lisenssin (versio 3 tai uudempi) ehdoin. Ohjelmalla ei ole minkäänlaista takuuta.",
    settings_ok: "OK",
    settings_cancel: "Peruuta",
};
