use super::Strings;

pub(super) static FR: Strings = Strings {
    lang_tag: "fr",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Ouvrir l'état",
    menu_settings: "Paramètres…",
    menu_help: "Aide",
    menu_quit: "Quitter NAS Access",

    cond_working: "Accès OK",
    cond_flaky: "Renouvellement incertain",
    cond_will_stop: "Accès bientôt terminé",
    cond_stopped: "Aucun accès",
    cond_off: "Désactivé",

    id_signed_in_as: "Connecté en tant que {account}",
    id_working_as: "Fonctionne en tant que {account}",

    access_ends_in: "L'accès se termine dans {duration}",
    grant_expires_in: "L'autorisation expire dans {days}",
    dur_hours_minutes: "{h} h {m} min",
    dur_minutes: "{m} min",
    dur_under_a_minute: "moins d'une minute",
    dur_one_day: "1 jour",
    dur_days: "{d} jours",

    blk_no_broker_url: "URL du broker non configurée",
    blk_network_error: "{broker} injoignable",
    blk_realm_unknown: "Aucun paramètre reçu de {broker}",
    blk_realm_not_registered: "Windows n'est pas configuré pour {realm}",
    blk_no_supply: "Nécessite une connexion via le navigateur",
    blk_no_grant: "Cet appareil n'est pas autorisé à fonctionner en tant que {account}",
    blk_grant_refused: "Votre organisation a refusé cette autorisation",
    blk_refused: "Votre compte a été refusé",
    blk_ntlm_fallback: "Les lecteurs réseau ne fonctionnent plus (NTLM)",

    details_heading: "Détails Kerberos",
    meter_label: "Accès valable pendant",
    d_realm: "Royaume",
    d_source: "Source",
    d_ticket: "Ticket",
    d_ticket_value: "Renouvelable · prend fin à {time}",
    d_ticket_value_norenew: "Prend fin à {time}",
    d_supply: "Renouvelé via",
    d_supply_grant: "l'autorisation de cet appareil",
    d_supply_wam: "votre compte Windows",
    d_supply_browser: "votre connexion au navigateur",
    d_supply_none: "rien — a besoin de vous",
    d_next: "Prochaine tentative",

    err_sign_off_failed: "Échec de la déconnexion : Windows a refusé d'effacer les tickets de ce domaine. Les partages ouverts peuvent continuer à fonctionner.",
    signed_off_note: "Déconnecté. Les lecteurs réseau déjà ouverts peuvent continuer à fonctionner jusqu'à ce que vous les fermiez ou redémarriez cet appareil.",
    granted_note: "Cet appareil peut désormais obtenir l'accès tout seul. Votre navigateur reste connecté à {idp} — il est recommandé de vous y déconnecter.",
    granted_note_wam: "Cet appareil peut désormais obtenir l'accès tout seul.",

    no_action: "Aucune action — cet appareil ne peut rien y faire",

    act_sign_in: "Se connecter…",
    act_sign_in_extend: "Prolonger l'accès…",
    act_create_grant: "Autoriser l'accès…",
    act_create_grant_again: "Autoriser à nouveau…",
    act_reinject: "Renouveler maintenant",
    act_cancel: "Annuler",
    act_drop_ticket: "Fermer l'accès",
    act_sign_out_idp: "Fermer la session {idp}",
    act_give_up_grant: "Supprimer l'autorisation…",
    act_enroll: "Configurer Windows…",
    act_reenroll: "Configurer Windows à nouveau…",
    act_unenroll: "Oublier {realm}…",
    act_restart_workstation: "Réparer les lecteurs réseau…",
    act_open_settings: "Ouvrir les paramètres",
    act_open_log: "Ouvrir le dossier du journal",

    err_broker_unreachable: "Réseau : {broker} n'a pas répondu. ({detail})",
    err_tls_untrusted: "TLS non fiable : cet appareil ne peut pas confirmer qu'il parle vraiment à {broker}. Un administrateur doit corriger cela.",
    err_broker_ambiguous_source: "Source du broker manquante : {broker} dessert plusieurs sources ({sources}) et cette adresse n'en nomme aucune. L'URL du broker doit en nommer une ; un administrateur doit corriger cela.",
    err_not_admitted: "Accès au royaume refusé : votre compte n'est pas admis dans ce royaume. Un administrateur doit accorder l'accès. ({detail})",
    err_invalid_proof: "Connexion rejetée : {broker} n'a pas accepté votre connexion. ({detail})",
    err_rate_limited: "Broker occupé : {broker} nous a demandé de ralentir. NAS Access réessaiera.",
    err_server_unavailable: "Broker dégradé : {broker} fonctionne, mais un service derrière lui non. ({detail})",
    err_bad_request: "Protocole du broker : NAS Access a envoyé une requête que {broker} a rejetée comme mal formée. ({detail})",
    err_broker_protocol: "Protocole du broker : {broker} a répondu d'une manière que NAS Access ne comprend pas. ({detail})",
    err_idp_refused: "IdP a refusé : {issuer} a rejeté la connexion. ({detail})",
    err_sign_in: "Échec de la connexion : {detail}",
    err_sign_in_timeout: "Délai de connexion dépassé : la connexion via le navigateur n'a pas été terminée.",
    err_silent_refresh: "Échec du renouvellement : {detail}",
    err_wam_empty: "WAM vide : une connexion silencieuse n'a pas été possible — le renouvellement nécessite le navigateur.",
    err_browser_required: "Le renouvellement nécessite une connexion via le navigateur.",
    err_internal: "Erreur NAS Access : une défaillance interne. ({detail})",
    err_grant_disabled: "Autorisations d'appareil désactivées : votre organisation n'autorise pas à ignorer la connexion via le navigateur ici.",
    err_grant_key: "Échec de la création de la clé : cet appareil n'a pas pu créer la clé protégée. ({detail})",
    err_grant_failed: "Échec de l'autorisation : cet appareil n'a pas été autorisé. ({detail})",
    err_grant_too_many: "Limite d'appareils atteinte : votre compte a déjà autant d'appareils autorisés que votre administrateur le permet. Retirez-en un avant d'ajouter cet appareil. ({detail})",
    err_grant_not_allowed: "Autorisation d'appareil refusée : votre compte n'est pas autorisé à ignorer la connexion via le navigateur. Un administrateur doit l'accorder. ({detail})",
    err_grant_not_delegate: "Pas délégué : vous êtes connecté, mais vous n'êtes pas autorisé à configurer cet appareil pour ce compte. Quelqu'un doit vous ajouter au groupe de délégués de ce compte. ({detail})",
    err_grant_reauthorize: "Utilisateur délégué : les paramètres autorisent l'accès pour {target} — impossible de se connecter en tant que quelqu'un d'autre.",
    err_elevation_failed: "Échec de l'élévation : l'étape administrateur n'a pas pu démarrer. ({detail})",
    err_elevation_unavailable: "Élévation indisponible : l'UAC est désactivé sur cet appareil (EnableLUA=0), donc NAS Access ne peut pas obtenir de droits d'administrateur. Un administrateur doit lancer cette opération depuis une invite élevée.",
    err_elevated_unconfirmed: "Impossible de confirmer : l'étape administrateur s'est terminée sans signaler de résultat.",

    fail_title_enroll: "Impossible de configurer Windows pour {realm}",
    fail_title_repair: "Impossible de réparer les lecteurs réseau",
    fail_title_unenroll: "Impossible de supprimer {realm}",

    dlg_waiting: "En attente d'autorisation…",
    dlg_close: "Fermer",
    btn_cancel: "Annuler",

    dlg_repair_question: "Réparer les lecteurs réseau ?",
    dlg_repair_body: "Cela redémarre le service Station de travail (LanmanWorkstation). Tous les lecteurs réseau et dossiers partagés de cet appareil sont déconnectés, pas seulement ceux de {realm}, et les programmes ayant des fichiers ouverts dessus peuvent perdre du travail non enregistré.",
    dlg_repair_dependents: "{services} s'arrête et redémarre avec lui.",
    dlg_repair_save: "Enregistrez votre travail d'abord.",
    dlg_repair_commit: "Réparer quand même",
    dlg_repair_working: "Réparation des lecteurs réseau…",
    repair_incomplete: "La réparation ne s'est pas terminée proprement. Le journal contient les détails.",
    dlg_repair_result: "Lecteurs réseau réparés. D'autres lecteurs réseau devront peut-être être rouverts.",

    dlg_enroll_question: "Configurer Windows pour {realm} ?",
    dlg_enroll_body: "Ces commandes s'exécutent en tant qu'administrateur :",
    dlg_enroll_reboot: "Un redémarrage est nécessaire ensuite : Windows n'en lit une partie qu'au démarrage.",
    dlg_enroll_commit: "Configurer Windows",
    dlg_enroll_working: "Configuration de Windows…",
    dlg_enroll_result: "Windows est maintenant configuré pour {realm}. Redémarrez pour terminer.",
    enroll_already: "Windows est déjà configuré pour {realm}. Rien à faire.",
    enroll_incomplete: "La configuration ne s'est pas terminée proprement. Le journal contient les détails.",
    enroll_discovery_failed: "Impossible de lire la configuration depuis le broker, aucune modification n'a donc été effectuée.",

    dlg_unenroll_question: "Supprimer {realm} de Windows ?",
    dlg_unenroll_body: "Ces clés de registre sont supprimées en tant qu'administrateur :",
    dlg_unenroll_note: "Windows ne fera plus confiance à {realm} pour Kerberos tant qu'il n'aura pas été reconfiguré.",
    dlg_unenroll_commit: "Supprimer {realm}",
    dlg_unenroll_working: "Suppression de {realm} de Windows…",
    dlg_unenroll_result: "Windows ne connaît plus {realm}.",
    unenroll_already: "Windows n'est pas configuré pour {realm}. Rien à supprimer.",
    unenroll_incomplete: "La suppression ne s'est pas terminée proprement. Le journal contient les détails.",

    dlg_grant_off_question: "Supprimer l'autorisation de cet appareil ?",
    dlg_grant_off_body: "La clé dans le TPM de cet appareil est supprimée et révoquée sur {broker}. Cette suppression est irréversible — autoriser à nouveau crée une nouvelle clé.",
    dlg_grant_off_body_own: "Votre accès aux lecteurs réseau de {realm} n'est pas affecté. Cet appareil se connecte comme il le faisait avant d'être autorisé.",
    dlg_grant_off_body_delegated: "Cet appareil fonctionne en tant que {target} et ne peut pas se connecter en tant que quelqu'un d'autre. Son accès aux lecteurs réseau de {realm} continue de fonctionner jusqu'à son expiration dans {remaining}, puis s'arrête. Pour le relancer, quelqu'un autorisé à autoriser {target} doit se connecter ici.",
    dlg_grant_off_commit: "Supprimer l'autorisation",
    dlg_grant_off_working: "Suppression de l'autorisation…",
    dlg_grant_off_result: "Autorisation supprimée.",
    dlg_grant_off_result_sub: "Clé supprimée sur cet appareil · révoquée sur {broker}",
    dlg_grant_off_result_stale: "Clé supprimée sur cet appareil · {broker} le répertorie toujours, et un administrateur l'efface avec `kbmanage device revoke`",
    dlg_grant_unsaved: "Cet appareil n'a pas pu mettre à jour son propre enregistrement.",

    grant_confirm: "Cet appareil peut atteindre vos lecteurs réseau sans connexion via le navigateur, pour votre compte sur cet appareil. Validité : {days}.\r\n\r\nLa clé reste dans le TPM de cet appareil et ne peut pas en être copiée. Votre administrateur peut la révoquer à tout moment.",
    dlg_grant_commit: "Autoriser l'accès",
    dlg_grant_working: "Autorisation de cet appareil…",
    grant_done: "Terminé. Cet appareil n'aura pas besoin de connexion via le navigateur pendant {days}.",

    notify_ready_title: "L'accès à {realm} est prêt",
    notify_ready_body: "{identity}. L'accès dure {duration}.",
    notify_expiring_title: "L'accès à {realm} se termine dans {duration}",
    notify_expiring_body: "Le renouvellement n'a pas fonctionné. {action} pour conserver l'accès.",
    notify_stopped_title: "L'accès à {realm} a pris fin",
    notify_stopped_body: "{action} pour retrouver l'accès.",
    notify_grant_due_title: "L'autorisation expire dans {days}",
    notify_grant_due_body: "Cet appareil atteint {realm} sans connexion via le navigateur. Autorisez l'accès à nouveau avant le {date} pour le conserver.",

    settings_title: "NAS Access — Paramètres",
    tab_basic: "Général",
    tab_advanced: "Avancé",
    tab_about: "À propos",
    settings_section_connection: "Connexion",
    settings_broker_label: "URL du broker",
    settings_broker_sub: "Serveur auquel se connecter — fourni par votre équipe informatique",
    settings_broker_managed: "Définie par votre équipe informatique — non modifiable ici.",
    settings_save: "Enregistrer",
    settings_gate: "L'autorisation et la configuration de Windows apparaissent une fois la configuration terminée",
    settings_section_signin: "Connexion au compte",
    settings_startup_label: "Lancer à l'ouverture de session",
    settings_startup_sub: "Se connecter automatiquement après votre ouverture de session.",
    settings_startup_managed: "Activé par votre équipe informatique pour tous les utilisateurs de cet ordinateur.",
    settings_wam_label: "Utiliser la connexion Windows quand c'est possible",
    settings_wam_sub: "Ignore le navigateur quand la connexion propre à Windows (WAM) ne demande rien.",
    settings_section_authorization: "Autorisation",
    settings_grant_state: "Accès autorisé en tant que {account}",
    settings_grant_for_label: "Autoriser cet appareil pour",
    settings_grant_for_sub: "Vide pour votre propre compte, ou un autre compte en tant que lequel cet appareil doit fonctionner.",
    settings_section_windows: "Configuration de Windows",
    settings_enrolled: "Windows est configuré pour {realm}.",
    settings_not_enrolled: "Windows n'est pas configuré pour {realm}.",
    settings_section_troubleshoot: "Dépannage",
    settings_troubleshoot_sub: "Enregistrements techniques détaillés de ce que cette application a fait, pour le moment où quelqu'un vous aide à résoudre un problème.",
    about_license: "Logiciel libre : vous pouvez le redistribuer et le modifier selon la Licence publique générale GNU, version 3 ou ultérieure. Ce programme est fourni sans aucune garantie.",
    settings_ok: "OK",
    settings_cancel: "Annuler",
};
