use super::Strings;

pub(super) static IT: Strings = Strings {
    lang_tag: "it",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Apri stato",
    menu_settings: "Impostazioni…",
    menu_help: "Guida",
    menu_quit: "Esci da NAS Access",

    cond_working: "Accesso OK",
    cond_flaky: "Rinnovo incerto",
    cond_will_stop: "Accesso in scadenza",
    cond_stopped: "Nessun accesso",
    cond_off: "Disattivato",

    id_signed_in_as: "Connesso come {account}",
    id_working_as: "Funziona come {account}",

    access_ends_in: "L'accesso termina tra {duration}",
    grant_expires_in: "L'autorizzazione scade tra {days}",
    dur_hours_minutes: "{h} h {m} min",
    dur_minutes: "{m} min",
    dur_under_a_minute: "meno di un minuto",
    dur_one_day: "1 giorno",
    dur_days: "{d} giorni",

    blk_no_broker_url: "URL del broker non configurato",
    blk_network_error: "Impossibile raggiungere {broker}",
    blk_realm_unknown: "Nessuna impostazione da {broker}",
    blk_realm_not_registered: "Windows non è configurato per {realm}",
    blk_no_supply: "Richiede un accesso dal browser",
    blk_no_grant: "Questo dispositivo non è autorizzato a funzionare come {account}",
    blk_grant_refused: "La tua organizzazione ha rifiutato questa autorizzazione",
    blk_refused: "Il tuo account è stato rifiutato",
    blk_ntlm_fallback: "Le unità di rete hanno smesso di funzionare (NTLM)",

    details_heading: "Dettagli Kerberos",
    meter_label: "Accesso valido per",
    d_realm: "Realm",
    d_source: "Origine",
    d_ticket: "Ticket",
    d_ticket_value: "Rinnovabile · termina alle {time}",
    d_ticket_value_norenew: "Termina alle {time}",
    d_supply: "Si rinnova con",
    d_supply_grant: "l'autorizzazione di questo dispositivo",
    d_supply_wam: "il tuo account Windows",
    d_supply_browser: "il tuo accesso dal browser",
    d_supply_none: "niente: serve il tuo intervento",
    d_next: "Prossimo tentativo",

    err_sign_off_failed: "Disconnessione non riuscita: Windows ha rifiutato di cancellare i ticket di questo reame. Le condivisioni aperte potrebbero continuare a funzionare.",
    signed_off_note: "Disconnesso. Le unità di rete già aperte potrebbero continuare a funzionare finché non le chiudi o riavvii questo dispositivo.",
    granted_note: "Questo dispositivo ora può ottenere l'accesso da solo. Il browser è ancora connesso a {idp}: è consigliabile disconnettersi.",
    granted_note_wam: "Questo dispositivo ora può ottenere l'accesso da solo.",

    no_action: "Nessuna azione: questo dispositivo non può farci nulla",

    act_sign_in: "Accedi…",
    act_sign_in_extend: "Estendi l'accesso…",
    act_create_grant: "Autorizza l'accesso…",
    act_create_grant_again: "Autorizza di nuovo…",
    act_reinject: "Rinnova ora",
    act_cancel: "Annulla",
    act_drop_ticket: "Chiudi l'accesso",
    act_sign_out_idp: "Disconnetti da {idp}",
    act_give_up_grant: "Rimuovi l'autorizzazione…",
    act_enroll: "Configura Windows…",
    act_reenroll: "Configura di nuovo Windows…",
    act_unenroll: "Dimentica {realm}…",
    act_restart_workstation: "Ripara le unità di rete…",
    act_open_settings: "Apri le impostazioni",
    act_open_log: "Apri la cartella del registro",

    err_broker_unreachable: "Rete: {broker} non ha risposto. ({detail})",
    err_tls_untrusted: "TLS non attendibile: questo dispositivo non può confermare di stare davvero parlando con {broker}. Deve risolverlo un amministratore.",
    err_broker_ambiguous_source: "Origine del broker mancante: {broker} serve più origini ({sources}) e questo indirizzo non ne nomina nessuna. L'URL del broker deve nominarne una; deve risolverlo un amministratore.",
    err_not_admitted: "Accesso al realm negato: il tuo account non è ammesso in questo realm. Un amministratore deve concedere l'accesso. ({detail})",
    err_invalid_proof: "Accesso rifiutato: {broker} non ha accettato il tuo accesso. ({detail})",
    err_rate_limited: "Broker occupato: {broker} ha chiesto di rallentare. NAS Access riproverà.",
    err_server_unavailable: "Broker degradato: {broker} è attivo, ma un servizio dietro di esso no. ({detail})",
    err_bad_request: "Protocollo del broker: NAS Access ha inviato una richiesta che {broker} ha rifiutato perché malformata. ({detail})",
    err_broker_protocol: "Protocollo del broker: {broker} ha risposto in un modo che NAS Access non comprende. ({detail})",
    err_idp_refused: "IdP ha rifiutato: {issuer} ha respinto l'accesso. ({detail})",
    err_sign_in: "Accesso non riuscito: {detail}",
    err_sign_in_timeout: "Accesso scaduto: l'accesso dal browser non è stato completato.",
    err_silent_refresh: "Rinnovo non riuscito: {detail}",
    err_wam_empty: "WAM vuoto: l'accesso silenzioso non è stato possibile — il rinnovo richiede il browser.",
    err_browser_required: "Il rinnovo richiede un accesso dal browser.",
    err_internal: "Errore di NAS Access: un guasto interno. ({detail})",
    err_grant_disabled: "Concessioni dispositivo disattivate: la tua organizzazione non consente di saltare qui l'accesso dal browser.",
    err_grant_key: "Creazione della chiave non riuscita: questo dispositivo non è riuscito a creare la chiave protetta. ({detail})",
    err_grant_failed: "Autorizzazione non riuscita: questo dispositivo non è stato autorizzato. ({detail})",
    err_grant_too_many: "Limite dispositivi raggiunto: il tuo account ha già tutti i dispositivi autorizzati che l'amministratore consente. Rimuovine uno prima di aggiungere questo dispositivo. ({detail})",
    err_grant_not_allowed: "Autorizzazione dispositivo negata: il tuo account non può saltare l'accesso dal browser. Deve concederlo un amministratore. ({detail})",
    err_grant_not_delegate: "Non sei un delegato: hai effettuato l'accesso, ma non puoi configurare questo dispositivo per quell'account. Qualcuno deve aggiungerti al gruppo dei delegati di quell'account. ({detail})",
    err_grant_reauthorize: "Utente delegato: le impostazioni autorizzano l'accesso per {target} — non è possibile accedere come qualcun altro.",
    err_elevation_failed: "Elevazione non riuscita: non è stato possibile avviare il passaggio da amministratore. ({detail})",
    err_elevation_unavailable: "Elevazione non disponibile: l'UAC è disattivato su questo dispositivo (EnableLUA=0), quindi NAS Access non può ottenere i diritti di amministratore. Un amministratore deve eseguire questa operazione da un prompt con privilegi elevati.",
    err_elevated_unconfirmed: "Impossibile confermare: il passaggio da amministratore è terminato senza segnalare un esito.",

    fail_title_enroll: "Impossibile configurare Windows per {realm}",
    fail_title_repair: "Impossibile riparare le unità di rete",
    fail_title_unenroll: "Impossibile rimuovere {realm}",

    dlg_waiting: "In attesa dell'autorizzazione…",
    dlg_close: "Chiudi",
    btn_cancel: "Annulla",

    dlg_repair_question: "Riparare le unità di rete?",
    dlg_repair_body: "Questa operazione riavvia il servizio Workstation (LanmanWorkstation). Ogni unità di rete e cartella condivisa su questo dispositivo viene disconnessa, non solo quelle di {realm}, e i programmi con file aperti su di esse potrebbero perdere il lavoro non salvato.",
    dlg_repair_dependents: "{services} viene arrestato e riavviato insieme a esso.",
    dlg_repair_save: "Salva prima il tuo lavoro.",
    dlg_repair_commit: "Ripara comunque",
    dlg_repair_working: "Riparazione delle unità di rete…",
    repair_incomplete: "La riparazione non è terminata correttamente. Il registro contiene i dettagli.",
    dlg_repair_result: "Unità di rete riparate. Le altre unità di rete potrebbero dover essere riaperte.",

    dlg_enroll_question: "Configurare Windows per {realm}?",
    dlg_enroll_body: "Questi comandi vengono eseguiti come amministratore:",
    dlg_enroll_reboot: "Dopo serve un riavvio: Windows legge una parte di tutto questo solo all'avvio.",
    dlg_enroll_commit: "Configura Windows",
    dlg_enroll_working: "Configurazione di Windows…",
    dlg_enroll_result: "Windows è ora configurato per {realm}. Riavvia per completare.",
    enroll_already: "Windows è già configurato per {realm}. Non c'è nulla da fare.",
    enroll_incomplete: "La configurazione non è terminata correttamente. Il registro contiene i dettagli.",
    enroll_discovery_failed: "Impossibile leggere la configurazione dal broker, quindi non è stato modificato nulla.",

    dlg_unenroll_question: "Rimuovere {realm} da Windows?",
    dlg_unenroll_body: "Queste chiavi del registro di sistema vengono eliminate come amministratore:",
    dlg_unenroll_note: "Windows non si fiderà più di {realm} per Kerberos finché non verrà configurato di nuovo.",
    dlg_unenroll_commit: "Rimuovi {realm}",
    dlg_unenroll_working: "Rimozione di {realm} da Windows…",
    dlg_unenroll_result: "Windows non conosce più {realm}.",
    unenroll_already: "Windows non è configurato per {realm}. Non c'è nulla da rimuovere.",
    unenroll_incomplete: "La rimozione non è terminata correttamente. Il registro contiene i dettagli.",

    dlg_grant_off_question: "Rimuovere l'autorizzazione di questo dispositivo?",
    dlg_grant_off_body: "La chiave nel TPM di questo dispositivo viene eliminata e revocata su {broker}. L'eliminazione non può essere annullata: autorizzare di nuovo crea una chiave nuova.",
    dlg_grant_off_body_own: "Il tuo accesso alle unità di rete di {realm} non viene toccato. Questo dispositivo accede come faceva prima di essere autorizzato.",
    dlg_grant_off_body_delegated: "Questo dispositivo funziona come {target} e non può accedere come qualcun altro. Il suo accesso alle unità di rete di {realm} continua a funzionare fino alla scadenza tra {remaining}, poi si interrompe. Per riavviarlo, deve accedere qui qualcuno autorizzato ad autorizzare {target}.",
    dlg_grant_off_commit: "Rimuovi l'autorizzazione",
    dlg_grant_off_working: "Rimozione dell'autorizzazione…",
    dlg_grant_off_result: "Autorizzazione rimossa.",
    dlg_grant_off_result_sub: "Chiave eliminata su questo dispositivo · revocata su {broker}",
    dlg_grant_off_result_stale: "Chiave eliminata su questo dispositivo · {broker} lo elenca ancora, e un amministratore lo rimuove con `kbmanage device revoke`",
    dlg_grant_unsaved: "Questo dispositivo non è riuscito ad aggiornare il proprio record.",

    grant_confirm: "Questo dispositivo può raggiungere le tue unità di rete senza accedere dal browser, per il tuo account su questo dispositivo. Validità: {days}.\r\n\r\nLa chiave resta nel TPM di questo dispositivo e non può esserne copiata. L'amministratore può revocarla in qualsiasi momento.",
    dlg_grant_commit: "Autorizza l'accesso",
    dlg_grant_working: "Autorizzazione di questo dispositivo…",
    grant_done: "Fatto. Questo dispositivo non avrà bisogno dell'accesso dal browser per {days}.",

    notify_ready_title: "L'accesso a {realm} è pronto",
    notify_ready_body: "{identity}. L'accesso dura {duration}.",
    notify_expiring_title: "L'accesso a {realm} termina tra {duration}",
    notify_expiring_body: "Il rinnovo non ha funzionato. {action} per mantenere l'accesso.",
    notify_stopped_title: "L'accesso a {realm} è terminato",
    notify_stopped_body: "{action} per ottenere di nuovo l'accesso.",
    notify_grant_due_title: "L'autorizzazione scade tra {days}",
    notify_grant_due_body: "Questo dispositivo raggiunge {realm} senza accedere dal browser. Autorizza di nuovo l'accesso prima del {date} per mantenerlo.",

    settings_title: "NAS Access — Impostazioni",
    tab_basic: "Base",
    tab_advanced: "Avanzate",
    tab_about: "Informazioni",
    settings_section_connection: "Connessione",
    settings_broker_label: "URL del broker",
    settings_broker_sub: "Server a cui connettersi — dal tuo team IT",
    settings_broker_managed: "Impostato dal tuo team IT — non modificabile qui.",
    settings_save: "Salva",
    settings_gate: "Autorizzazione e configurazione di Windows compaiono quando la configurazione è completa",
    settings_section_signin: "Accesso",
    settings_startup_label: "Avvia all'accesso",
    settings_startup_sub: "Accedi automaticamente dopo aver eseguito l'accesso al computer.",
    settings_startup_managed: "Attivato dal tuo team IT per tutti gli utenti di questo computer.",
    settings_wam_label: "Usa l'accesso di Windows quando è possibile",
    settings_wam_sub: "Salta il browser quando l'accesso di Windows stesso (WAM) non deve chiedere nulla.",
    settings_section_authorization: "Autorizzazione",
    settings_grant_state: "Accesso autorizzato come {account}",
    settings_grant_for_label: "Autorizza questo dispositivo per",
    settings_grant_for_sub: "Vuoto per il tuo account, oppure un altro account come cui questo dispositivo deve funzionare.",
    settings_section_windows: "Configurazione di Windows",
    settings_enrolled: "Windows è configurato per {realm}.",
    settings_not_enrolled: "Windows non è configurato per {realm}.",
    settings_section_troubleshoot: "Risoluzione dei problemi",
    settings_troubleshoot_sub: "Registrazioni tecniche dettagliate di ciò che questa app ha fatto, per quando qualcuno ti aiuta a risolvere un problema.",
    about_license: "Software libero: puoi ridistribuirlo e modificarlo secondo la GNU General Public License, versione 3 o successiva. Questo programma è fornito senza alcuna garanzia.",
    settings_ok: "OK",
    settings_cancel: "Annulla",
};
