use super::Strings;

pub(super) static JA: Strings = Strings {
    lang_tag: "ja",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "状態を開く",
    menu_settings: "設定…",
    menu_help: "ヘルプ",
    menu_quit: "NAS Access を終了",

    cond_working: "アクセス正常",
    cond_flaky: "更新が不確実",
    cond_will_stop: "アクセスの期限が近づいています",
    cond_stopped: "アクセスなし",
    cond_off: "オフ",

    id_signed_in_as: "{account} としてサインイン中",
    id_working_as: "{account} として動作中",

    access_ends_in: "アクセスは {duration} 後に終了します",
    grant_expires_in: "承認は {days} 後に期限切れになります",
    dur_hours_minutes: "{h} 時間 {m} 分",
    dur_minutes: "{m} 分",
    dur_under_a_minute: "1 分未満",
    dur_one_day: "1 日",
    dur_days: "{d} 日",

    blk_no_broker_url: "ブローカーの URL が未設定です",
    blk_network_error: "{broker} に接続できません",
    blk_realm_unknown: "{broker} からの設定がありません",
    blk_realm_not_registered: "Windows が {realm} 用に設定されていません",
    blk_no_supply: "ブラウザーでのサインインが必要です",
    blk_no_grant: "このデバイスは {account} として動作する承認がありません",
    blk_grant_refused: "組織がこの承認を拒否しました",
    blk_refused: "アカウントが拒否されました",
    blk_ntlm_fallback: "ネットワーク ドライブが動作しなくなりました (NTLM)",

    details_heading: "Kerberos の詳細",
    meter_label: "アクセスの有効期間",
    d_realm: "レルム",
    d_source: "ソース",
    d_ticket: "チケット",
    d_ticket_value: "更新可能 · {time} に終了",
    d_ticket_value_norenew: "{time} に終了",
    d_supply: "更新に使うもの",
    d_supply_grant: "このデバイスの承認",
    d_supply_wam: "お使いの Windows アカウント",
    d_supply_browser: "ブラウザーのサインイン",
    d_supply_none: "なし — 操作が必要です",
    d_next: "次の試行",

    err_sign_off_failed: "サインオフに失敗しました。Windows がこのレルムのチケットの消去を拒否しました。開いている共有は引き続き使用できる場合があります。",
    signed_off_note: "サインアウトしました。すでに開いているネットワーク ドライブは、閉じるかこのデバイスを再起動するまで使える場合があります。",
    granted_note: "このデバイスは自力でアクセスを取得できるようになりました。ブラウザーは {idp} にサインインしたままです。サインアウトすることをお勧めします。",
    granted_note_wam: "このデバイスは自力でアクセスを取得できるようになりました。",

    no_action: "操作なし — このデバイスにできることはありません",

    act_sign_in: "サインイン…",
    act_sign_in_extend: "アクセスを延長…",
    act_create_grant: "アクセスを承認…",
    act_create_grant_again: "もう一度承認…",
    act_reinject: "今すぐ更新",
    act_cancel: "キャンセル",
    act_drop_ticket: "アクセスを終了",
    act_sign_out_idp: "{idp} からサインアウト",
    act_give_up_grant: "承認を削除…",
    act_enroll: "Windows を設定…",
    act_reenroll: "Windows をもう一度設定…",
    act_unenroll: "{realm} を削除…",
    act_restart_workstation: "ネットワーク ドライブを修復…",
    act_open_settings: "設定を開く",
    act_open_log: "ログ フォルダーを開く",

    err_broker_unreachable: "ネットワーク: {broker} が応答しませんでした。({detail})",
    err_tls_untrusted: "TLS が信頼できません: このデバイスは本当に {broker} と通信しているか確認できません。管理者が対処する必要があります。",
    err_broker_ambiguous_source: "ブローカーのソース未指定: {broker} は複数のソース（{sources}）を扱いますが、このアドレスはいずれも指定していません。ブローカーの URL でいずれかを指定する必要があります。管理者が対処する必要があります。",
    err_not_admitted: "レルムへのアクセス拒否: このアカウントはこのレルムで許可されていません。管理者がアクセスを許可する必要があります。({detail})",
    err_invalid_proof: "サインイン拒否: {broker} がサインインを受け付けませんでした。({detail})",
    err_rate_limited: "ブローカー混雑: {broker} から速度を落とすよう要求されました。NAS Access は再試行します。",
    err_server_unavailable: "ブローカー低下: {broker} は稼働していますが、その背後のサービスが動いていません。({detail})",
    err_bad_request: "ブローカー プロトコル: NAS Access が送った要求を {broker} が不正な形式として拒否しました。({detail})",
    err_broker_protocol: "ブローカー プロトコル: {broker} の応答を NAS Access が解釈できません。({detail})",
    err_idp_refused: "IdP が拒否: {issuer} がサインインを拒否しました。({detail})",
    err_sign_in: "サインインに失敗しました: {detail}",
    err_sign_in_timeout: "サインインがタイムアウトしました: ブラウザーでのサインインが完了しませんでした。",
    err_silent_refresh: "更新に失敗しました: {detail}",
    err_wam_empty: "WAM が空です: サイレント サインインができませんでした。更新にはブラウザーが必要です。",
    err_browser_required: "更新にはブラウザーでのサインインが必要です。",
    err_internal: "NAS Access エラー: 内部エラーです。({detail})",
    err_grant_disabled: "デバイス承認は無効: この環境では、組織がブラウザーのサインインの省略を許可していません。",
    err_grant_key: "キーの作成に失敗: このデバイスは保護されたキーを作成できませんでした。({detail})",
    err_grant_failed: "承認に失敗: このデバイスは承認されませんでした。({detail})",
    err_grant_too_many: "デバイス上限に到達: 承認済みデバイスの数が、管理者の許可する上限に達しています。このデバイスを追加する前に 1 台を解除してください。({detail})",
    err_grant_not_allowed: "デバイス承認を拒否: このアカウントにはブラウザーのサインインを省略する権限がありません。管理者による許可が必要です。({detail})",
    err_grant_not_delegate: "委任されていません: サインインは成功しましたが、このデバイスをそのアカウント用に設定する権限がありません。そのアカウントの委任グループに追加してもらう必要があります。({detail})",
    err_grant_reauthorize: "委任ユーザー: 設定では {target} のアクセスが承認されています。ほかの人としてはサインインできません。",
    err_elevation_failed: "昇格に失敗: 管理者の手順を開始できませんでした。({detail})",
    err_elevation_unavailable: "昇格を利用できません: このデバイスでは UAC が無効です (EnableLUA=0)。そのため NAS Access は管理者権限を取得できません。管理者が昇格したコマンド プロンプトから実行する必要があります。",
    err_elevated_unconfirmed: "確認できません: 管理者の手順は結果を報告せずに終了しました。",

    fail_title_enroll: "{realm} 用の Windows 設定に失敗しました",
    fail_title_repair: "ネットワーク ドライブを修復できませんでした",
    fail_title_unenroll: "{realm} を削除できませんでした",

    dlg_waiting: "許可を待っています…",
    dlg_close: "閉じる",
    btn_cancel: "キャンセル",

    dlg_repair_question: "ネットワーク ドライブを修復しますか?",
    dlg_repair_body: "Workstation サービス (LanmanWorkstation) を再起動します。{realm} のものだけでなく、このデバイス上のすべてのネットワーク ドライブと共有フォルダーが切断され、そこにファイルを開いているプログラムは未保存の作業を失う可能性があります。",
    dlg_repair_dependents: "{services} も一緒に停止し、再び開始されます。",
    dlg_repair_save: "先に作業を保存してください。",
    dlg_repair_commit: "それでも修復",
    dlg_repair_working: "ネットワーク ドライブを修復しています…",
    repair_incomplete: "修復が正常に完了しませんでした。詳細はログにあります。",
    dlg_repair_result: "ネットワーク ドライブを修復しました。ほかのネットワーク ドライブは開き直しが必要な場合があります。",

    dlg_enroll_question: "{realm} 用に Windows を設定しますか?",
    dlg_enroll_body: "次のコマンドを管理者として実行します:",
    dlg_enroll_reboot: "その後に再起動が必要です: Windows はこの一部を起動時にしか読み込みません。",
    dlg_enroll_commit: "Windows を設定",
    dlg_enroll_working: "Windows を設定しています…",
    dlg_enroll_result: "Windows は {realm} 用に設定されました。再起動して完了してください。",
    enroll_already: "Windows はすでに {realm} 用に設定されています。行うことはありません。",
    enroll_incomplete: "設定が正常に完了しませんでした。詳細はログにあります。",
    enroll_discovery_failed: "ブローカーから設定を読み取れなかったため、何も変更されませんでした。",

    dlg_unenroll_question: "{realm} を Windows から削除しますか?",
    dlg_unenroll_body: "次のレジストリ キーを管理者として削除します:",
    dlg_unenroll_note: "再度設定するまで、Windows は Kerberos で {realm} を信頼しなくなります。",
    dlg_unenroll_commit: "{realm} を削除",
    dlg_unenroll_working: "{realm} を Windows から削除しています…",
    dlg_unenroll_result: "Windows は {realm} を認識しなくなりました。",
    unenroll_already: "Windows は {realm} 用に設定されていません。削除するものはありません。",
    unenroll_incomplete: "削除が正常に完了しませんでした。詳細はログにあります。",

    dlg_grant_off_question: "このデバイスの承認を削除しますか?",
    dlg_grant_off_body: "このデバイスの TPM 内のキーが削除され、{broker} で取り消されます。削除は元に戻せません。もう一度承認すると新しいキーが作成されます。",
    dlg_grant_off_body_own: "{realm} のネットワーク ドライブへのアクセスは影響を受けません。このデバイスは承認前と同じ方法でサインインします。",
    dlg_grant_off_body_delegated: "このデバイスは {target} として動作し、ほかの人としてはサインインできません。{realm} のネットワーク ドライブへのアクセスは {remaining} 後の期限まで動作し、その後停止します。再開するには、{target} を承認できる人がここでサインインする必要があります。",
    dlg_grant_off_commit: "承認を削除",
    dlg_grant_off_working: "承認を削除しています…",
    dlg_grant_off_result: "承認を削除しました。",
    dlg_grant_off_result_sub: "このデバイスでキーを削除 · {broker} で取り消し済み",
    dlg_grant_off_result_stale: "このデバイスでキーを削除 · {broker} にはまだ登録が残っており、管理者が `kbmanage device revoke` で消します",
    dlg_grant_unsaved: "このデバイスは自身の記録を更新できませんでした。",

    grant_confirm: "このデバイスは、このデバイス上のあなたのアカウントで、ブラウザーのサインインなしにネットワーク ドライブへアクセスできます。有効期間: {days}。\r\n\r\nキーはこのデバイスの TPM に保管され、外部にコピーすることはできません。管理者はいつでも取り消せます。",
    dlg_grant_commit: "アクセスを承認",
    dlg_grant_working: "このデバイスを承認しています…",
    grant_done: "完了しました。このデバイスは {days} の間、ブラウザーでのサインインが不要になります。",

    notify_ready_title: "{realm} のアクセスの準備ができました",
    notify_ready_body: "{identity}。アクセスは {duration} 有効です。",
    notify_expiring_title: "{realm} へのアクセスは {duration} 後に終了します",
    notify_expiring_body: "更新できていません。アクセスを維持するには「{action}」を実行してください。",
    notify_stopped_title: "{realm} へのアクセスが終了しました",
    notify_stopped_body: "もう一度アクセスするには「{action}」を実行してください。",
    notify_grant_due_title: "承認は {days} 後に期限切れになります",
    notify_grant_due_body: "このデバイスはブラウザーのサインインなしで {realm} に接続できます。維持するには {date} までにアクセスを再度承認してください。",

    settings_title: "NAS Access — 設定",
    tab_basic: "基本",
    tab_advanced: "詳細",
    tab_about: "情報",
    settings_section_connection: "接続",
    settings_broker_label: "ブローカーの URL",
    settings_broker_sub: "接続先のサーバー — IT チームから提供されます",
    settings_broker_managed: "IT チームによって設定されています。ここでは変更できません。",
    settings_save: "保存",
    settings_gate: "設定が完了すると、承認と Windows の設定が表示されます",
    settings_section_signin: "サインイン",
    settings_startup_label: "ログイン時に起動",
    settings_startup_sub: "ログイン後に自動的にサインインします。",
    settings_startup_managed: "IT チームによって、このコンピューターのすべてのユーザー向けに有効にされています。",
    settings_wam_label: "可能なときは Windows のサインインを使う",
    settings_wam_sub: "Windows 自身のサインイン (WAM) が確認を必要としないときはブラウザーを使いません。",
    settings_section_authorization: "承認",
    settings_grant_state: "{account} としてアクセスが承認されています",
    settings_grant_for_label: "このデバイスを承認する対象",
    settings_grant_for_sub: "自分のアカウントの場合は空欄、またはこのデバイスが動作すべき別のアカウントを入力します。",
    settings_section_windows: "Windows の設定",
    settings_enrolled: "Windows は {realm} 用に設定されています。",
    settings_not_enrolled: "Windows は {realm} 用に設定されていません。",
    settings_section_troubleshoot: "トラブルシューティング",
    settings_troubleshoot_sub: "このアプリが行った処理の詳細な技術記録です。誰かに問題の解決を手伝ってもらうときに使います。",
    about_license: "フリーソフトウェアです。GNU 一般公衆利用許諾書 (バージョン 3 以降) の条件の下で再配布・改変できます。本プログラムは無保証です。",
    settings_ok: "OK",
    settings_cancel: "キャンセル",
};
