use super::Strings;

pub(super) static KO: Strings = Strings {
    lang_tag: "ko",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "상태 열기",
    menu_settings: "설정…",
    menu_help: "도움말",
    menu_quit: "NAS Access 종료",

    cond_working: "액세스 정상",
    cond_flaky: "갱신 불확실",
    cond_will_stop: "액세스 만료 예정",
    cond_stopped: "액세스 없음",
    cond_off: "꺼짐",

    id_signed_in_as: "{account}(으)로 로그인됨",
    id_working_as: "{account}(으)로 동작 중",

    access_ends_in: "액세스가 {duration} 후에 종료됩니다",
    grant_expires_in: "승인이 {days} 후에 만료됩니다",
    dur_hours_minutes: "{h}시간 {m}분",
    dur_minutes: "{m}분",
    dur_under_a_minute: "1분 미만",
    dur_one_day: "1일",
    dur_days: "{d}일",

    blk_no_broker_url: "브로커 URL이 설정되지 않음",
    blk_network_error: "{broker}에 연결할 수 없음",
    blk_realm_unknown: "{broker}에서 받은 설정이 없음",
    blk_realm_not_registered: "Windows가 {realm}용으로 설정되지 않음",
    blk_no_supply: "브라우저 로그인이 필요함",
    blk_no_grant: "이 장치는 {account}(으)로 동작할 권한이 없음",
    blk_grant_refused: "조직에서 이 승인을 거부함",
    blk_refused: "계정이 거부됨",
    blk_ntlm_fallback: "네트워크 드라이브가 작동을 멈춤 (NTLM)",

    details_heading: "Kerberos 세부 정보",
    meter_label: "액세스 유효 기간",
    d_realm: "영역",
    d_source: "소스",
    d_ticket: "티켓",
    d_ticket_value: "갱신 가능 · {time}에 종료",
    d_ticket_value_norenew: "{time}에 종료",
    d_supply: "갱신 수단",
    d_supply_grant: "이 장치의 승인",
    d_supply_wam: "Windows 계정",
    d_supply_browser: "브라우저 로그인",
    d_supply_none: "없음 — 직접 조치가 필요합니다",
    d_next: "다음 시도",

    err_sign_off_failed: "로그오프 실패: Windows가 이 영역의 티켓 삭제를 거부했습니다. 열려 있는 공유는 계속 작동할 수 있습니다.",
    signed_off_note: "로그아웃했습니다. 이미 열어 둔 네트워크 드라이브는 닫거나 이 장치를 다시 시작할 때까지 계속 작동할 수 있습니다.",
    granted_note: "이제 이 장치가 스스로 액세스를 받을 수 있습니다. 브라우저는 아직 {idp}에 로그인되어 있습니다 — 로그아웃하는 것을 권장합니다.",
    granted_note_wam: "이제 이 장치가 스스로 액세스를 받을 수 있습니다.",

    no_action: "가능한 작업 없음 — 이 장치가 할 수 있는 일이 없습니다",

    act_sign_in: "로그인…",
    act_sign_in_extend: "액세스 연장…",
    act_create_grant: "액세스 승인…",
    act_create_grant_again: "다시 승인…",
    act_reinject: "지금 갱신",
    act_cancel: "취소",
    act_drop_ticket: "액세스 종료",
    act_sign_out_idp: "{idp}에서 로그아웃",
    act_give_up_grant: "승인 제거…",
    act_enroll: "Windows 설정…",
    act_reenroll: "Windows 다시 설정…",
    act_unenroll: "{realm} 삭제…",
    act_restart_workstation: "네트워크 드라이브 복구…",
    act_open_settings: "설정 열기",
    act_open_log: "로그 폴더 열기",

    err_broker_unreachable: "네트워크: {broker}이(가) 응답하지 않았습니다. ({detail})",
    err_tls_untrusted: "TLS 신뢰 불가: 이 장치는 실제로 {broker}과(와) 통신하고 있는지 확인할 수 없습니다. 관리자가 해결해야 합니다.",
    err_broker_ambiguous_source: "브로커 소스 미지정: {broker}은(는) 여러 소스({sources})를 제공하지만 이 주소는 그중 어느 것도 지정하지 않습니다. 브로커 URL이 그중 하나를 지정해야 합니다. 관리자가 해결해야 합니다.",
    err_not_admitted: "영역 액세스 거부: 이 계정은 이 영역에 허용되지 않습니다. 관리자가 액세스를 허용해야 합니다. ({detail})",
    err_invalid_proof: "로그인 거부됨: {broker}이(가) 로그인을 수락하지 않았습니다. ({detail})",
    err_rate_limited: "브로커 사용량 많음: {broker}이(가) 속도를 낮추도록 요청했습니다. NAS Access가 다시 시도합니다.",
    err_server_unavailable: "브로커 성능 저하: {broker}은(는) 작동 중이지만 그 뒤의 서비스가 작동하지 않습니다. ({detail})",
    err_bad_request: "브로커 프로토콜: NAS Access가 보낸 요청을 {broker}이(가) 잘못된 형식으로 거부했습니다. ({detail})",
    err_broker_protocol: "브로커 프로토콜: {broker}의 응답을 NAS Access가 이해하지 못합니다. ({detail})",
    err_idp_refused: "IdP 거부: {issuer}이(가) 로그인을 거부했습니다. ({detail})",
    err_sign_in: "로그인 실패: {detail}",
    err_sign_in_timeout: "로그인 시간 초과: 브라우저 로그인이 완료되지 않았습니다.",
    err_silent_refresh: "갱신 실패: {detail}",
    err_wam_empty: "WAM 비어 있음: 자동 로그인이 불가능했습니다 — 갱신에는 브라우저가 필요합니다.",
    err_browser_required: "갱신하려면 브라우저 로그인이 필요합니다.",
    err_internal: "NAS Access 오류: 내부 오류입니다. ({detail})",
    err_grant_disabled: "장치 승인 꺼짐: 조직에서 여기서의 브라우저 로그인 건너뛰기를 허용하지 않습니다.",
    err_grant_key: "키 생성 실패: 이 장치에서 보호된 키를 만들지 못했습니다. ({detail})",
    err_grant_failed: "승인 실패: 이 장치가 승인되지 않았습니다. ({detail})",
    err_grant_too_many: "장치 한도 도달: 관리자가 허용한 만큼의 장치가 이미 승인되어 있습니다. 이 장치를 추가하기 전에 하나를 해제하세요. ({detail})",
    err_grant_not_allowed: "장치 승인 거부됨: 이 계정은 브라우저 로그인을 건너뛸 수 없습니다. 관리자가 권한을 부여해야 합니다. ({detail})",
    err_grant_not_delegate: "위임자가 아님: 로그인은 되었지만 이 장치를 해당 계정용으로 설정할 권한이 없습니다. 누군가 해당 계정의 위임 그룹에 추가해 주어야 합니다. ({detail})",
    err_grant_reauthorize: "위임 사용자: 설정이 {target}에 대한 액세스를 승인합니다 — 다른 사람으로는 로그인할 수 없습니다.",
    err_elevation_failed: "권한 상승 실패: 관리자 단계를 시작할 수 없었습니다. ({detail})",
    err_elevation_unavailable: "권한 상승 불가: 이 장치에서 UAC가 비활성화되어 있어(EnableLUA=0) NAS Access가 관리자 권한을 얻을 수 없습니다. 관리자가 권한이 상승된 명령 프롬프트에서 실행해야 합니다.",
    err_elevated_unconfirmed: "확인할 수 없음: 관리자 단계가 결과를 보고하지 않고 끝났습니다.",

    fail_title_enroll: "{realm}용 Windows 설정에 실패했습니다",
    fail_title_repair: "네트워크 드라이브를 복구하지 못했습니다",
    fail_title_unenroll: "{realm}을(를) 제거하지 못했습니다",

    dlg_waiting: "권한을 기다리는 중…",
    dlg_close: "닫기",
    btn_cancel: "취소",

    dlg_repair_question: "네트워크 드라이브를 복구할까요?",
    dlg_repair_body: "Workstation 서비스(LanmanWorkstation)를 다시 시작합니다. {realm}의 것뿐 아니라 이 장치의 모든 네트워크 드라이브와 공유 폴더가 끊기며, 거기에 파일을 열어 둔 프로그램은 저장하지 않은 작업을 잃을 수 있습니다.",
    dlg_repair_dependents: "{services}도 함께 중지되었다가 다시 시작됩니다.",
    dlg_repair_save: "먼저 작업을 저장하세요.",
    dlg_repair_commit: "그래도 복구",
    dlg_repair_working: "네트워크 드라이브를 복구하는 중…",
    repair_incomplete: "복구가 깔끔하게 끝나지 않았습니다. 자세한 내용은 로그에 있습니다.",
    dlg_repair_result: "네트워크 드라이브를 복구했습니다. 다른 네트워크 드라이브는 다시 열어야 할 수 있습니다.",

    dlg_enroll_question: "{realm}용으로 Windows를 설정할까요?",
    dlg_enroll_body: "다음 명령이 관리자 권한으로 실행됩니다:",
    dlg_enroll_reboot: "그 후에 다시 시작해야 합니다: Windows는 이 중 일부를 부팅할 때만 읽습니다.",
    dlg_enroll_commit: "Windows 설정",
    dlg_enroll_working: "Windows를 설정하는 중…",
    dlg_enroll_result: "이제 Windows가 {realm}용으로 설정되었습니다. 다시 시작하여 완료하세요.",
    enroll_already: "Windows는 이미 {realm}용으로 설정되어 있습니다. 할 일이 없습니다.",
    enroll_incomplete: "설정이 깔끔하게 끝나지 않았습니다. 자세한 내용은 로그에 있습니다.",
    enroll_discovery_failed: "브로커에서 설정을 읽을 수 없어 아무것도 변경되지 않았습니다.",

    dlg_unenroll_question: "Windows에서 {realm}을(를) 제거할까요?",
    dlg_unenroll_body: "다음 레지스트리 키가 관리자 권한으로 삭제됩니다:",
    dlg_unenroll_note: "다시 설정하기 전까지 Windows는 Kerberos에서 {realm}을(를) 신뢰하지 않습니다.",
    dlg_unenroll_commit: "{realm} 제거",
    dlg_unenroll_working: "Windows에서 {realm}을(를) 제거하는 중…",
    dlg_unenroll_result: "Windows가 더 이상 {realm}을(를) 알지 못합니다.",
    unenroll_already: "Windows는 {realm}용으로 설정되어 있지 않습니다. 제거할 것이 없습니다.",
    unenroll_incomplete: "제거가 깔끔하게 끝나지 않았습니다. 자세한 내용은 로그에 있습니다.",

    dlg_grant_off_question: "이 장치의 승인을 제거할까요?",
    dlg_grant_off_body: "이 장치의 TPM에 있는 키가 삭제되고 {broker}에서 해지됩니다. 삭제는 되돌릴 수 없습니다 — 다시 승인하면 새 키가 만들어집니다.",
    dlg_grant_off_body_own: "{realm} 네트워크 드라이브에 대한 액세스는 영향을 받지 않습니다. 이 장치는 승인 전과 같은 방식으로 로그인합니다.",
    dlg_grant_off_body_delegated: "이 장치는 {target}(으)로 동작하며 다른 사람으로는 로그인할 수 없습니다. {realm} 네트워크 드라이브에 대한 액세스는 {remaining} 후 만료될 때까지 유지되다가 중단됩니다. 다시 시작하려면 {target}을(를) 승인할 수 있는 사람이 여기서 로그인해야 합니다.",
    dlg_grant_off_commit: "승인 제거",
    dlg_grant_off_working: "승인을 제거하는 중…",
    dlg_grant_off_result: "승인을 제거했습니다.",
    dlg_grant_off_result_sub: "이 장치에서 키 삭제됨 · {broker}에서 해지됨",
    dlg_grant_off_result_stale: "이 장치에서 키 삭제됨 · {broker}에는 아직 등록이 남아 있으며, 관리자가 `kbmanage device revoke`로 정리합니다",
    dlg_grant_unsaved: "이 장치가 자체 기록을 업데이트하지 못했습니다.",

    grant_confirm: "이 장치는 이 장치의 사용자 계정으로, 브라우저 로그인 없이 네트워크 드라이브에 연결할 수 있습니다. 유효 기간: {days}.\r\n\r\n키는 이 장치의 TPM에 남아 있으며 밖으로 복사할 수 없습니다. 관리자가 언제든지 해지할 수 있습니다.",
    dlg_grant_commit: "액세스 승인",
    dlg_grant_working: "이 장치를 승인하는 중…",
    grant_done: "완료되었습니다. 이 장치는 {days} 동안 브라우저 로그인이 필요하지 않습니다.",

    notify_ready_title: "{realm} 액세스가 준비되었습니다",
    notify_ready_body: "{identity}. 액세스는 {duration} 동안 유효합니다.",
    notify_expiring_title: "{realm} 액세스가 {duration} 후에 종료됩니다",
    notify_expiring_body: "갱신되지 않았습니다. 액세스를 유지하려면 '{action}'을(를) 선택하세요.",
    notify_stopped_title: "{realm} 액세스가 종료되었습니다",
    notify_stopped_body: "다시 액세스하려면 '{action}'을(를) 선택하세요.",
    notify_grant_due_title: "승인이 {days} 후에 만료됩니다",
    notify_grant_due_body: "이 장치는 브라우저 로그인 없이 {realm}에 연결합니다. 유지하려면 {date} 전에 액세스를 다시 승인하세요.",

    settings_title: "NAS Access — 설정",
    tab_basic: "기본",
    tab_advanced: "고급",
    tab_about: "정보",
    settings_section_connection: "연결",
    settings_broker_label: "브로커 URL",
    settings_broker_sub: "연결할 서버 — IT 팀에서 제공",
    settings_broker_managed: "IT 팀에서 설정함 — 여기서는 변경할 수 없습니다.",
    settings_save: "저장",
    settings_gate: "구성이 완료되면 승인과 Windows 설정이 표시됩니다",
    settings_section_signin: "로그인",
    settings_startup_label: "로그인 시 시작",
    settings_startup_sub: "로그인 후 자동으로 로그인합니다.",
    settings_startup_managed: "IT 팀에서 이 컴퓨터의 모든 사용자에 대해 사용하도록 설정했습니다.",
    settings_wam_label: "가능하면 Windows 로그인 사용",
    settings_wam_sub: "Windows 자체 로그인(WAM)이 확인을 요구하지 않을 때 브라우저를 건너뜁니다.",
    settings_section_authorization: "승인",
    settings_grant_state: "{account}(으)로 액세스가 승인됨",
    settings_grant_for_label: "이 장치를 승인할 대상",
    settings_grant_for_sub: "본인 계정이면 비워 두고, 이 장치가 대신 동작할 다른 계정을 입력할 수도 있습니다.",
    settings_section_windows: "Windows 설정",
    settings_enrolled: "Windows가 {realm}용으로 설정되어 있습니다.",
    settings_not_enrolled: "Windows가 {realm}용으로 설정되어 있지 않습니다.",
    settings_section_troubleshoot: "문제 해결",
    settings_troubleshoot_sub: "이 앱이 무엇을 했는지에 대한 자세한 기술 기록으로, 누군가 문제 해결을 도와줄 때 사용합니다.",
    about_license: "자유 소프트웨어입니다. GNU 일반 공중 사용 허가서(버전 3 이상)에 따라 재배포하고 수정할 수 있습니다. 이 프로그램은 어떠한 보증도 제공하지 않습니다.",
    settings_ok: "확인",
    settings_cancel: "취소",
};
