use super::Strings;

pub(super) static PT: Strings = Strings {
    lang_tag: "pt",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Abrir status",
    menu_settings: "Configurações…",
    menu_help: "Ajuda",
    menu_quit: "Fechar o NAS Access",

    cond_working: "Acesso OK",
    cond_flaky: "Renovação incerta",
    cond_will_stop: "Acesso a expirar",
    cond_stopped: "Sem acesso",
    cond_off: "Desativado",

    id_signed_in_as: "Conectado como {account}",
    id_working_as: "Funciona como {account}",

    access_ends_in: "O acesso termina em {duration}",
    grant_expires_in: "A autorização expira em {days}",
    dur_hours_minutes: "{h} h {m} min",
    dur_minutes: "{m} min",
    dur_under_a_minute: "menos de um minuto",
    dur_one_day: "1 dia",
    dur_days: "{d} dias",

    blk_no_broker_url: "URL do broker não configurada",
    blk_network_error: "Não é possível alcançar {broker}",
    blk_realm_unknown: "Sem configurações de {broker}",
    blk_realm_not_registered: "O Windows não está configurado para {realm}",
    blk_no_supply: "Precisa de um login pelo navegador",
    blk_no_grant: "Este dispositivo não está autorizado a funcionar como {account}",
    blk_grant_refused: "Sua organização recusou esta autorização",
    blk_refused: "Sua conta foi recusada",
    blk_ntlm_fallback: "As unidades de rede pararam de funcionar (NTLM)",

    details_heading: "Detalhes do Kerberos",
    meter_label: "Acesso válido por",
    d_realm: "Reino",
    d_source: "Origem",
    d_ticket: "Ticket",
    d_ticket_value: "Renovável · termina às {time}",
    d_ticket_value_norenew: "Termina às {time}",
    d_supply: "Renova usando",
    d_supply_grant: "a autorização deste dispositivo",
    d_supply_wam: "sua conta do Windows",
    d_supply_browser: "seu login pelo navegador",
    d_supply_none: "nada — precisa de você",
    d_next: "Próxima tentativa",

    err_sign_off_failed: "Falha ao sair: o Windows recusou-se a limpar os tickets deste reino. As partilhas abertas podem continuar a funcionar.",
    signed_off_note: "Sessão encerrada. As unidades de rede que você já abriu podem continuar funcionando até que você as feche ou reinicie este dispositivo.",
    granted_note: "Este dispositivo já consegue obter acesso sozinho. Seu navegador continua conectado a {idp} — recomendamos sair por lá.",
    granted_note_wam: "Este dispositivo já consegue obter acesso sozinho.",

    no_action: "Nenhuma ação — este dispositivo não pode fazer nada a respeito",

    act_sign_in: "Entrar…",
    act_sign_in_extend: "Estender o acesso…",
    act_create_grant: "Autorizar o acesso…",
    act_create_grant_again: "Autorizar de novo…",
    act_reinject: "Renovar agora",
    act_cancel: "Cancelar",
    act_drop_ticket: "Encerrar o acesso",
    act_sign_out_idp: "Sair de {idp}",
    act_give_up_grant: "Remover a autorização…",
    act_enroll: "Configurar o Windows…",
    act_reenroll: "Configurar o Windows de novo…",
    act_unenroll: "Esquecer {realm}…",
    act_restart_workstation: "Reparar as unidades de rede…",
    act_open_settings: "Abrir as configurações",
    act_open_log: "Abrir a pasta do registro",

    err_broker_unreachable: "Rede: {broker} não respondeu. ({detail})",
    err_tls_untrusted: "TLS não confiável: este dispositivo não consegue confirmar que está mesmo falando com {broker}. Um administrador precisa corrigir isso.",
    err_broker_ambiguous_source: "Origem do broker ausente: {broker} atende várias origens ({sources}) e este endereço não nomeia nenhuma. A URL do broker precisa nomear uma; um administrador precisa corrigir isso.",
    err_not_admitted: "Acesso ao reino negado: sua conta não é admitida neste reino. Um administrador precisa conceder o acesso. ({detail})",
    err_invalid_proof: "Login recusado: {broker} não aceitou seu login. ({detail})",
    err_rate_limited: "Broker ocupado: {broker} pediu para reduzirmos o ritmo. O NAS Access vai tentar de novo.",
    err_server_unavailable: "Broker degradado: {broker} está no ar, mas um serviço por trás dele não está. ({detail})",
    err_bad_request: "Protocolo do broker: o NAS Access enviou uma solicitação que {broker} recusou como malformada. ({detail})",
    err_broker_protocol: "Protocolo do broker: {broker} respondeu de um jeito que o NAS Access não entende. ({detail})",
    err_idp_refused: "IdP recusou: {issuer} rejeitou o login. ({detail})",
    err_sign_in: "Falha no login: {detail}",
    err_sign_in_timeout: "Tempo de login esgotado: o login pelo navegador não foi concluído.",
    err_silent_refresh: "Falha na renovação: {detail}",
    err_wam_empty: "WAM vazio: não foi possível entrar em silêncio — a renovação precisa do navegador.",
    err_browser_required: "A renovação precisa de um login pelo navegador.",
    err_internal: "Erro do NAS Access: uma falha interna. ({detail})",
    err_grant_disabled: "Concessões de dispositivo desativadas: sua organização não permite dispensar o login pelo navegador aqui.",
    err_grant_key: "Falha ao criar a chave: este dispositivo não conseguiu criar a chave protegida. ({detail})",
    err_grant_failed: "Falha na autorização: este dispositivo não foi autorizado. ({detail})",
    err_grant_too_many: "Limite de dispositivos atingido: sua conta já tem tantos dispositivos autorizados quanto o administrador permite. Remova um antes de adicionar este dispositivo. ({detail})",
    err_grant_not_allowed: "Autorização de dispositivo negada: sua conta não tem permissão para dispensar o login pelo navegador. Um administrador precisa conceder isso. ({detail})",
    err_grant_not_delegate: "Não é delegado: você entrou, mas não pode configurar este dispositivo para essa conta. Alguém precisa adicionar você ao grupo de delegados dessa conta. ({detail})",
    err_grant_reauthorize: "Usuário delegado: as configurações autorizam o acesso para {target} — não é possível entrar como outra pessoa.",
    err_elevation_failed: "Falha na elevação: não foi possível iniciar a etapa de administrador. ({detail})",
    err_elevation_unavailable: "Elevação indisponível: o UAC está desativado neste dispositivo (EnableLUA=0), então o NAS Access não consegue obter direitos de administrador. Um administrador precisa executar isso a partir de um prompt elevado.",
    err_elevated_unconfirmed: "Não foi possível confirmar: a etapa de administrador terminou sem informar um resultado.",

    fail_title_enroll: "Não foi possível configurar o Windows para {realm}",
    fail_title_repair: "Não foi possível reparar as unidades de rede",
    fail_title_unenroll: "Não foi possível remover {realm}",

    dlg_waiting: "Aguardando permissão…",
    dlg_close: "Fechar",
    btn_cancel: "Cancelar",

    dlg_repair_question: "Reparar as unidades de rede?",
    dlg_repair_body: "Isto reinicia o serviço Estação de Trabalho (LanmanWorkstation). Todas as unidades de rede e pastas compartilhadas deste dispositivo são desconectadas, não apenas as de {realm}, e programas com arquivos abertos nelas podem perder trabalho não salvo.",
    dlg_repair_dependents: "{services} é parado e iniciado novamente junto com ele.",
    dlg_repair_save: "Salve seu trabalho primeiro.",
    dlg_repair_commit: "Reparar mesmo assim",
    dlg_repair_working: "Reparando as unidades de rede…",
    repair_incomplete: "O reparo não terminou de forma limpa. O registro tem os detalhes.",
    dlg_repair_result: "Unidades de rede reparadas. Outras unidades de rede podem precisar ser reabertas.",

    dlg_enroll_question: "Configurar o Windows para {realm}?",
    dlg_enroll_body: "Estes comandos são executados como administrador:",
    dlg_enroll_reboot: "Depois é preciso reiniciar: o Windows só lê parte disto na inicialização.",
    dlg_enroll_commit: "Configurar o Windows",
    dlg_enroll_working: "Configurando o Windows…",
    dlg_enroll_result: "O Windows agora está configurado para {realm}. Reinicie para concluir.",
    enroll_already: "O Windows já está configurado para {realm}. Nada a fazer.",
    enroll_incomplete: "A configuração não terminou de forma limpa. O registro tem os detalhes.",
    enroll_discovery_failed: "Não foi possível ler a configuração do broker, então nada foi alterado.",

    dlg_unenroll_question: "Remover {realm} do Windows?",
    dlg_unenroll_body: "Estas chaves de registro são excluídas como administrador:",
    dlg_unenroll_note: "O Windows deixará de confiar em {realm} para Kerberos até que seja configurado de novo.",
    dlg_unenroll_commit: "Remover {realm}",
    dlg_unenroll_working: "Removendo {realm} do Windows…",
    dlg_unenroll_result: "O Windows não conhece mais {realm}.",
    unenroll_already: "O Windows não está configurado para {realm}. Nada a remover.",
    unenroll_incomplete: "A remoção não terminou de forma limpa. O registro tem os detalhes.",

    dlg_grant_off_question: "Remover a autorização deste dispositivo?",
    dlg_grant_off_body: "A chave no TPM deste dispositivo é excluída e revogada em {broker}. Excluí-la não pode ser desfeito — autorizar de novo cria uma chave nova.",
    dlg_grant_off_body_own: "Seu acesso às unidades de rede de {realm} não é afetado. Este dispositivo entra do jeito que entrava antes de ser autorizado.",
    dlg_grant_off_body_delegated: "Este dispositivo funciona como {target} e não pode entrar como outra pessoa. O acesso dele às unidades de rede de {realm} continua funcionando até expirar em {remaining}, e então para. Para reativá-lo, alguém com permissão para autorizar {target} precisa entrar aqui.",
    dlg_grant_off_commit: "Remover a autorização",
    dlg_grant_off_working: "Removendo a autorização…",
    dlg_grant_off_result: "Autorização removida.",
    dlg_grant_off_result_sub: "Chave excluída neste dispositivo · revogada em {broker}",
    dlg_grant_off_result_stale: "Chave excluída neste dispositivo · {broker} ainda o lista, e um administrador o remove com `kbmanage device revoke`",
    dlg_grant_unsaved: "Este dispositivo não conseguiu atualizar o próprio registro.",

    grant_confirm: "Este dispositivo consegue alcançar suas unidades de rede sem login pelo navegador, para sua conta neste dispositivo. Validade: {days}.\r\n\r\nA chave fica no TPM deste dispositivo e não pode ser copiada para fora dele. Seu administrador pode revogá-la a qualquer momento.",
    dlg_grant_commit: "Autorizar o acesso",
    dlg_grant_working: "Autorizando este dispositivo…",
    grant_done: "Pronto. Este dispositivo não vai precisar de login pelo navegador por {days}.",

    notify_ready_title: "O acesso a {realm} está pronto",
    notify_ready_body: "{identity}. O acesso dura {duration}.",
    notify_expiring_title: "O acesso a {realm} termina em {duration}",
    notify_expiring_body: "A renovação não funcionou. {action} para manter o acesso.",
    notify_stopped_title: "O acesso a {realm} terminou",
    notify_stopped_body: "{action} para ter acesso de novo.",
    notify_grant_due_title: "A autorização expira em {days}",
    notify_grant_due_body: "Este dispositivo alcança {realm} sem login pelo navegador. Autorize o acesso de novo antes de {date} para mantê-lo.",

    settings_title: "NAS Access — Configurações",
    tab_basic: "Básico",
    tab_advanced: "Avançado",
    tab_about: "Sobre",
    settings_section_connection: "Conexão",
    settings_broker_label: "URL do broker",
    settings_broker_sub: "Servidor ao qual conectar — da sua equipe de TI",
    settings_broker_managed: "Definido pela sua equipe de TI — não pode ser alterado aqui.",
    settings_save: "Salvar",
    settings_gate: "Autorização e configuração do Windows aparecem quando a configuração estiver completa",
    settings_section_signin: "Login",
    settings_startup_label: "Abrir ao iniciar sessão",
    settings_startup_sub: "Entrar automaticamente após você fazer login.",
    settings_startup_managed: "Ativado pela sua equipe de TI para todos os usuários deste computador.",
    settings_wam_label: "Usar o login do Windows quando possível",
    settings_wam_sub: "Ignora o navegador quando o login do próprio Windows (WAM) não precisa perguntar nada.",
    settings_section_authorization: "Autorização",
    settings_grant_state: "Acesso autorizado como {account}",
    settings_grant_for_label: "Autorizar este dispositivo para",
    settings_grant_for_sub: "Vazio para sua própria conta, ou outra conta como a qual este dispositivo deve funcionar.",
    settings_section_windows: "Configuração do Windows",
    settings_enrolled: "O Windows está configurado para {realm}.",
    settings_not_enrolled: "O Windows não está configurado para {realm}.",
    settings_section_troubleshoot: "Solução de problemas",
    settings_troubleshoot_sub: "Registros técnicos detalhados do que este aplicativo fez, para quando alguém estiver ajudando você a resolver um problema.",
    about_license: "Software livre: você pode redistribuí-lo e modificá-lo sob a Licença Pública Geral GNU, versão 3 ou posterior. Este programa é fornecido sem qualquer garantia.",
    settings_ok: "OK",
    settings_cancel: "Cancelar",
};
