use super::Strings;

pub(super) static RU: Strings = Strings {
    lang_tag: "ru",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "Открыть состояние",
    menu_settings: "Параметры…",
    menu_help: "Справка",
    menu_quit: "Закрыть NAS Access",

    cond_working: "Доступ в порядке",
    cond_flaky: "Продление под вопросом",
    cond_will_stop: "Доступ истекает",
    cond_stopped: "Нет доступа",
    cond_off: "Выключено",

    id_signed_in_as: "Выполнен вход как {account}",
    id_working_as: "Работает как {account}",

    access_ends_in: "Доступ закончится через {duration}",
    grant_expires_in: "Авторизация истекает через {days}",
    dur_hours_minutes: "{h} ч {m} мин",
    dur_minutes: "{m} мин",
    dur_under_a_minute: "меньше минуты",
    dur_one_day: "1 день",
    dur_days: "{d} дн.",

    blk_no_broker_url: "URL брокера не настроен",
    blk_network_error: "Не удаётся связаться с {broker}",
    blk_realm_unknown: "Нет настроек от {broker}",
    blk_realm_not_registered: "Windows не настроена для {realm}",
    blk_no_supply: "Нужен вход через браузер",
    blk_no_grant: "Это устройство не авторизовано для работы как {account}",
    blk_grant_refused: "Ваша организация отклонила эту авторизацию",
    blk_refused: "Вашей учётной записи отказано",
    blk_ntlm_fallback: "Сетевые диски перестали работать (NTLM)",

    details_heading: "Сведения о Kerberos",
    meter_label: "Доступ действителен ещё",
    d_realm: "Область",
    d_source: "Источник",
    d_ticket: "Билет",
    d_ticket_value: "С возможностью продления · завершится в {time}",
    d_ticket_value_norenew: "Завершится в {time}",
    d_supply: "Продлевается через",
    d_supply_grant: "авторизацию этого устройства",
    d_supply_wam: "вашу учётную запись Windows",
    d_supply_browser: "ваш вход через браузер",
    d_supply_none: "ничего — нужны вы",
    d_next: "Следующая попытка",

    err_sign_off_failed: "Не удалось выйти: Windows отказалась удалить билеты этой области. Открытые общие ресурсы могут продолжать работать.",
    signed_off_note: "Выполнен выход. Уже открытые сетевые диски могут продолжать работать, пока вы их не закроете или не перезапустите это устройство.",
    granted_note: "Теперь это устройство получает доступ самостоятельно. Ваш браузер всё ещё выполнил вход в {idp} — рекомендуется выйти там.",
    granted_note_wam: "Теперь это устройство получает доступ самостоятельно.",

    no_action: "Нет действий — это устройство ничего не может с этим сделать",

    act_sign_in: "Войти…",
    act_sign_in_extend: "Продлить доступ…",
    act_create_grant: "Авторизовать доступ…",
    act_create_grant_again: "Авторизовать снова…",
    act_reinject: "Продлить сейчас",
    act_cancel: "Отмена",
    act_drop_ticket: "Завершить доступ",
    act_sign_out_idp: "Выйти из {idp}",
    act_give_up_grant: "Удалить авторизацию…",
    act_enroll: "Настроить Windows…",
    act_reenroll: "Настроить Windows заново…",
    act_unenroll: "Забыть {realm}…",
    act_restart_workstation: "Восстановить сетевые диски…",
    act_open_settings: "Открыть параметры",
    act_open_log: "Открыть папку журнала",

    err_broker_unreachable: "Сеть: {broker} не ответил. ({detail})",
    err_tls_untrusted: "TLS не доверен: это устройство не может подтвердить, что действительно общается с {broker}. Это должен исправить администратор.",
    err_broker_ambiguous_source: "Источник брокера не указан: {broker} обслуживает несколько источников ({sources}), а этот адрес не называет ни одного. В URL брокера должен быть указан один из них; это должен исправить администратор.",
    err_not_admitted: "Доступ к области запрещён: вашей учётной записи не разрешено работать в этой области. Администратор должен предоставить доступ. ({detail})",
    err_invalid_proof: "Вход отклонён: {broker} не принял ваш вход. ({detail})",
    err_rate_limited: "Брокер занят: {broker} попросил снизить темп. NAS Access повторит попытку.",
    err_server_unavailable: "Брокер работает частично: {broker} доступен, но одна из служб за ним — нет. ({detail})",
    err_bad_request: "Протокол брокера: NAS Access отправил запрос, который {broker} отклонил как некорректный. ({detail})",
    err_broker_protocol: "Протокол брокера: {broker} ответил так, что NAS Access этого не понимает. ({detail})",
    err_idp_refused: "Поставщик удостоверений отказал: {issuer} отклонил вход. ({detail})",
    err_sign_in: "Не удалось войти: {detail}",
    err_sign_in_timeout: "Время входа истекло: вход через браузер не был завершён.",
    err_silent_refresh: "Не удалось продлить: {detail}",
    err_wam_empty: "WAM пуст: тихий вход оказался невозможен — для продления нужен браузер.",
    err_browser_required: "Для продления нужен вход через браузер.",
    err_internal: "Ошибка NAS Access: внутренний сбой. ({detail})",
    err_grant_disabled: "Разрешения устройств отключены: ваша организация не разрешает пропускать здесь вход через браузер.",
    err_grant_key: "Не удалось создать ключ: это устройство не смогло создать защищённый ключ. ({detail})",
    err_grant_failed: "Не удалось авторизовать: это устройство не было авторизовано. ({detail})",
    err_grant_too_many: "Достигнут предел устройств: у вашей учётной записи уже столько авторизованных устройств, сколько разрешил администратор. Освободите одно, прежде чем добавлять это устройство. ({detail})",
    err_grant_not_allowed: "Авторизация устройства отклонена: вашей учётной записи не разрешено пропускать вход через браузер. Это должен разрешить администратор. ({detail})",
    err_grant_not_delegate: "Не делегат: вход выполнен, но у вас нет права настраивать это устройство для этой учётной записи. Вас должны добавить в группу делегатов этой учётной записи. ({detail})",
    err_grant_reauthorize: "Делегированный пользователь: параметры авторизуют доступ для {target} — войти под кем-то другим нельзя.",
    err_elevation_failed: "Не удалось повысить права: шаг с правами администратора не запустился. ({detail})",
    err_elevation_unavailable: "Повышение прав недоступно: на этом устройстве отключён UAC (EnableLUA=0), поэтому NAS Access не может получить права администратора. Администратор должен запустить это из командной строки с повышенными правами.",
    err_elevated_unconfirmed: "Не удалось подтвердить: шаг с правами администратора завершился без результата.",

    fail_title_enroll: "Не удалось настроить Windows для {realm}",
    fail_title_repair: "Не удалось восстановить сетевые диски",
    fail_title_unenroll: "Не удалось удалить {realm}",

    dlg_waiting: "Ожидание разрешения…",
    dlg_close: "Закрыть",
    btn_cancel: "Отмена",

    dlg_repair_question: "Восстановить сетевые диски?",
    dlg_repair_body: "Будет перезапущена служба «Рабочая станция» (LanmanWorkstation). Отключатся все сетевые диски и общие папки на этом устройстве, а не только относящиеся к {realm}, и программы с открытыми на них файлами могут потерять несохранённую работу.",
    dlg_repair_dependents: "{services} останавливается и запускается вместе с ней.",
    dlg_repair_save: "Сначала сохраните работу.",
    dlg_repair_commit: "Всё равно восстановить",
    dlg_repair_working: "Восстановление сетевых дисков…",
    repair_incomplete: "Восстановление завершилось не полностью. Подробности — в журнале.",
    dlg_repair_result: "Сетевые диски восстановлены. Другие сетевые диски может понадобиться открыть заново.",

    dlg_enroll_question: "Настроить Windows для {realm}?",
    dlg_enroll_body: "Эти команды выполняются от имени администратора:",
    dlg_enroll_reboot: "После этого нужна перезагрузка: часть из этого Windows читает только при запуске.",
    dlg_enroll_commit: "Настроить Windows",
    dlg_enroll_working: "Настройка Windows…",
    dlg_enroll_result: "Windows настроена для {realm}. Перезагрузите, чтобы завершить.",
    enroll_already: "Windows уже настроена для {realm}. Делать нечего.",
    enroll_incomplete: "Настройка завершилась не полностью. Подробности — в журнале.",
    enroll_discovery_failed: "Не удалось прочитать настройки с брокера, поэтому ничего не изменено.",

    dlg_unenroll_question: "Удалить {realm} из Windows?",
    dlg_unenroll_body: "Эти разделы реестра удаляются от имени администратора:",
    dlg_unenroll_note: "Windows перестанет доверять {realm} для Kerberos, пока настройка не будет выполнена снова.",
    dlg_unenroll_commit: "Удалить {realm}",
    dlg_unenroll_working: "Удаление {realm} из Windows…",
    dlg_unenroll_result: "Windows больше не знает о {realm}.",
    unenroll_already: "Windows не настроена для {realm}. Удалять нечего.",
    unenroll_incomplete: "Удаление завершилось не полностью. Подробности — в журнале.",

    dlg_grant_off_question: "Удалить авторизацию этого устройства?",
    dlg_grant_off_body: "Ключ в TPM этого устройства будет удалён и отозван на {broker}. Удаление необратимо — повторная авторизация создаёт новый ключ.",
    dlg_grant_off_body_own: "Ваш доступ к сетевым дискам {realm} не затрагивается. Это устройство будет входить так же, как до авторизации.",
    dlg_grant_off_body_delegated: "Это устройство работает как {target} и не может войти под кем-то другим. Его доступ к сетевым дискам {realm} продолжит работать ещё {remaining}, а затем прекратится. Чтобы запустить его снова, здесь должен войти тот, кому разрешено авторизовать {target}.",
    dlg_grant_off_commit: "Удалить авторизацию",
    dlg_grant_off_working: "Удаление авторизации…",
    dlg_grant_off_result: "Авторизация удалена.",
    dlg_grant_off_result_sub: "Ключ удалён на этом устройстве · отозван на {broker}",
    dlg_grant_off_result_stale: "Ключ удалён на этом устройстве · {broker} всё ещё показывает его, и администратор убирает запись командой `kbmanage device revoke`",
    dlg_grant_unsaved: "Это устройство не смогло обновить собственную запись.",

    grant_confirm: "Это устройство сможет обращаться к вашим сетевым дискам без входа через браузер, от вашей учётной записи на этом устройстве. Срок: {days}.\r\n\r\nКлюч остаётся в TPM этого устройства, и скопировать его оттуда нельзя. Администратор может отозвать его в любой момент.",
    dlg_grant_commit: "Авторизовать доступ",
    dlg_grant_working: "Авторизация этого устройства…",
    grant_done: "Готово. Этому устройству не понадобится вход через браузер в течение {days}.",

    notify_ready_title: "Доступ к {realm} готов",
    notify_ready_body: "{identity}. Доступ действует {duration}.",
    notify_expiring_title: "Доступ к {realm} закончится через {duration}",
    notify_expiring_body: "Продлить не удалось. Чтобы сохранить доступ, выберите «{action}».",
    notify_stopped_title: "Доступ к {realm} закончился",
    notify_stopped_body: "Чтобы снова получить доступ, выберите «{action}».",
    notify_grant_due_title: "Авторизация истекает через {days}",
    notify_grant_due_body: "Это устройство обращается к {realm} без входа через браузер. Чтобы сохранить это, авторизуйте доступ снова до {date}.",

    settings_title: "NAS Access — Параметры",
    tab_basic: "Основные",
    tab_advanced: "Дополнительно",
    tab_about: "О программе",
    settings_section_connection: "Подключение",
    settings_broker_label: "URL брокера",
    settings_broker_sub: "Сервер для подключения — от вашей ИТ-команды",
    settings_broker_managed: "Задано вашей ИТ-командой — здесь изменить нельзя.",
    settings_save: "Сохранить",
    settings_gate: "Авторизация и настройка Windows появятся, когда конфигурация будет завершена",
    settings_section_signin: "Вход",
    settings_startup_label: "Запускать при входе в систему",
    settings_startup_sub: "Автоматически выполнять вход после входа в систему.",
    settings_startup_managed: "Включено вашей ИТ-командой для всех пользователей этого компьютера.",
    settings_wam_label: "Использовать вход Windows, когда это возможно",
    settings_wam_sub: "Пропускает браузер, когда собственный вход Windows (WAM) не требует запросов.",
    settings_section_authorization: "Авторизация",
    settings_grant_state: "Доступ авторизован как {account}",
    settings_grant_for_label: "Авторизовать это устройство для",
    settings_grant_for_sub: "Пусто — для вашей собственной учётной записи, либо другая учётная запись, как которая должно работать это устройство.",
    settings_section_windows: "Настройка Windows",
    settings_enrolled: "Windows настроена для {realm}.",
    settings_not_enrolled: "Windows не настроена для {realm}.",
    settings_section_troubleshoot: "Диагностика",
    settings_troubleshoot_sub: "Подробные технические записи о том, что делало это приложение, — на случай, когда кто-то помогает вам разобраться с проблемой.",
    about_license: "Свободное программное обеспечение: вы можете распространять и изменять его на условиях GNU General Public License версии 3 или новее. Программа поставляется без каких-либо гарантий.",
    settings_ok: "ОК",
    settings_cancel: "Отмена",
};
