use super::Strings;

pub(super) static ZH: Strings = Strings {
    lang_tag: "zh-Hans",
    app_name: "NAS Access",
    tagline: "by KerBridge",

    menu_open_status: "打开状态",
    menu_settings: "设置…",
    menu_help: "帮助",
    menu_quit: "退出 NAS Access",

    cond_working: "访问正常",
    cond_flaky: "续期不确定",
    cond_will_stop: "访问即将到期",
    cond_stopped: "无访问权限",
    cond_off: "已关闭",

    id_signed_in_as: "已以 {account} 登录",
    id_working_as: "以 {account} 身份运行",

    access_ends_in: "访问将在 {duration} 后结束",
    grant_expires_in: "授权将在 {days} 后过期",
    dur_hours_minutes: "{h} 小时 {m} 分钟",
    dur_minutes: "{m} 分钟",
    dur_under_a_minute: "不到一分钟",
    dur_one_day: "1 天",
    dur_days: "{d} 天",

    blk_no_broker_url: "尚未配置代理服务器 URL",
    blk_network_error: "无法连接 {broker}",
    blk_realm_unknown: "未从 {broker} 获取设置",
    blk_realm_not_registered: "Windows 尚未为 {realm} 配置",
    blk_no_supply: "需要浏览器登录",
    blk_no_grant: "此设备未获授权以 {account} 身份运行",
    blk_grant_refused: "贵组织拒绝了此授权",
    blk_refused: "你的账户被拒绝",
    blk_ntlm_fallback: "网络驱动器已停止工作 (NTLM)",

    details_heading: "Kerberos 详情",
    meter_label: "访问有效期",
    d_realm: "领域",
    d_source: "来源",
    d_ticket: "票据",
    d_ticket_value: "可续期 · 于 {time} 结束",
    d_ticket_value_norenew: "于 {time} 结束",
    d_supply: "续期方式",
    d_supply_grant: "此设备的授权",
    d_supply_wam: "你的 Windows 帐户",
    d_supply_browser: "你的浏览器登录",
    d_supply_none: "无 — 需要你操作",
    d_next: "下次尝试",

    err_sign_off_failed: "注销失败：Windows 拒绝清除此领域的票据。已打开的共享可能仍可使用。",
    signed_off_note: "已注销。已打开的网络驱动器可能仍可使用，直到你关闭它们或重启此设备。",
    granted_note: "此设备现在可以自行获取访问权限。你的浏览器仍登录着 {idp} — 建议在那里退出登录。",
    granted_note_wam: "此设备现在可以自行获取访问权限。",

    no_action: "无可执行操作 — 此设备对此无能为力",

    act_sign_in: "登录…",
    act_sign_in_extend: "延长访问…",
    act_create_grant: "授权访问…",
    act_create_grant_again: "重新授权…",
    act_reinject: "立即续期",
    act_cancel: "取消",
    act_drop_ticket: "结束访问",
    act_sign_out_idp: "退出 {idp} 登录",
    act_give_up_grant: "移除授权…",
    act_enroll: "配置 Windows…",
    act_reenroll: "重新配置 Windows…",
    act_unenroll: "忘记 {realm}…",
    act_restart_workstation: "修复网络驱动器…",
    act_open_settings: "打开设置",
    act_open_log: "打开日志文件夹",

    err_broker_unreachable: "网络：{broker} 没有响应。({detail})",
    err_tls_untrusted: "TLS 不受信任：此设备无法确认它真的在与 {broker} 通信。需要管理员解决此问题。",
    err_broker_ambiguous_source: "未指定代理服务器来源：{broker} 服务多个来源（{sources}），而此地址未指明其中任何一个。代理服务器 URL 必须指明其中之一；需要管理员解决此问题。",
    err_not_admitted: "领域访问被拒绝：你的账户不被允许进入此领域。需要管理员授予访问权限。({detail})",
    err_invalid_proof: "登录被拒绝：{broker} 不接受你的登录。({detail})",
    err_rate_limited: "代理服务器繁忙：{broker} 要求我们放慢速度。NAS Access 将重试。",
    err_server_unavailable: "代理服务器降级：{broker} 正常运行，但其后端的某个服务未运行。({detail})",
    err_bad_request: "代理服务器协议：NAS Access 发送的请求被 {broker} 判定为格式错误并拒绝。({detail})",
    err_broker_protocol: "代理服务器协议：{broker} 的响应方式 NAS Access 无法理解。({detail})",
    err_idp_refused: "身份提供方拒绝：{issuer} 拒绝了此次登录。({detail})",
    err_sign_in: "登录失败：{detail}",
    err_sign_in_timeout: "登录超时：浏览器登录未完成。",
    err_silent_refresh: "续期失败：{detail}",
    err_wam_empty: "WAM 为空：无法静默登录 — 续期需要浏览器。",
    err_browser_required: "续期需要浏览器登录。",
    err_internal: "NAS Access 错误：内部故障。({detail})",
    err_grant_disabled: "设备授权已关闭：贵组织不允许在此跳过浏览器登录。",
    err_grant_key: "密钥创建失败：此设备无法创建受保护的密钥。({detail})",
    err_grant_failed: "授权失败：此设备未获授权。({detail})",
    err_grant_too_many: "已达设备上限：你的账户已达到管理员允许的授权设备数量上限。请先移除一台，再添加此设备。({detail})",
    err_grant_not_allowed: "设备授权被拒绝：你的账户无权跳过浏览器登录。需由管理员授予该权限。({detail})",
    err_grant_not_delegate: "不是受委托人：你已登录，但无权将此设备设置为该账户。需要有人把你加入该账户的委托组。({detail})",
    err_grant_reauthorize: "受委托用户：设置为 {target} 授权访问 — 无法以其他人身份登录。",
    err_elevation_failed: "提升权限失败：无法启动管理员步骤。({detail})",
    err_elevation_unavailable: "无法提升权限：此设备已禁用 UAC (EnableLUA=0)，因此 NAS Access 无法获得管理员权限。需要管理员从提升权限的命令提示符中运行。",
    err_elevated_unconfirmed: "无法确认：管理员步骤结束时未报告结果。",

    fail_title_enroll: "无法为 {realm} 配置 Windows",
    fail_title_repair: "无法修复网络驱动器",
    fail_title_unenroll: "无法移除 {realm}",

    dlg_waiting: "正在等待授权…",
    dlg_close: "关闭",
    btn_cancel: "取消",

    dlg_repair_question: "要修复网络驱动器吗？",
    dlg_repair_body: "此操作会重启工作站服务 (LanmanWorkstation)。此设备上的所有网络驱动器和共享文件夹都会断开，不只是 {realm} 的，在其上打开文件的程序可能会丢失未保存的工作。",
    dlg_repair_dependents: "{services} 会随之停止并重新启动。",
    dlg_repair_save: "请先保存你的工作。",
    dlg_repair_commit: "仍要修复",
    dlg_repair_working: "正在修复网络驱动器…",
    repair_incomplete: "修复未能干净地完成。日志中有详细信息。",
    dlg_repair_result: "网络驱动器已修复。其他网络驱动器可能需要重新打开。",

    dlg_enroll_question: "要为 {realm} 配置 Windows 吗？",
    dlg_enroll_body: "以下命令将以管理员身份运行：",
    dlg_enroll_reboot: "之后需要重启：Windows 只在启动时读取其中一部分。",
    dlg_enroll_commit: "配置 Windows",
    dlg_enroll_working: "正在配置 Windows…",
    dlg_enroll_result: "Windows 现已为 {realm} 配置完成。请重启以完成。",
    enroll_already: "Windows 已为 {realm} 配置。无需操作。",
    enroll_incomplete: "配置未能干净地完成。日志中有详细信息。",
    enroll_discovery_failed: "无法从代理服务器读取设置，因此未做任何更改。",

    dlg_unenroll_question: "要从 Windows 中移除 {realm} 吗？",
    dlg_unenroll_body: "以下注册表项将以管理员身份删除：",
    dlg_unenroll_note: "在重新配置之前，Windows 将不再为 Kerberos 信任 {realm}。",
    dlg_unenroll_commit: "移除 {realm}",
    dlg_unenroll_working: "正在从 Windows 中移除 {realm}…",
    dlg_unenroll_result: "Windows 已不再识别 {realm}。",
    unenroll_already: "Windows 未为 {realm} 配置。无需移除。",
    unenroll_incomplete: "移除未能干净地完成。日志中有详细信息。",

    dlg_grant_off_question: "要移除此设备的授权吗？",
    dlg_grant_off_body: "此设备 TPM 中的密钥将被删除，并在 {broker} 上吊销。删除后无法撤销 — 重新授权会创建新的密钥。",
    dlg_grant_off_body_own: "你对 {realm} 网络驱动器的访问不受影响。此设备将按获得授权之前的方式登录。",
    dlg_grant_off_body_delegated: "此设备以 {target} 身份运行，无法以其他人身份登录。它对 {realm} 网络驱动器的访问会一直有效到 {remaining} 后到期，然后停止。要重新启用，需要有权为 {target} 授权的人在此登录。",
    dlg_grant_off_commit: "移除授权",
    dlg_grant_off_working: "正在移除授权…",
    dlg_grant_off_result: "授权已移除。",
    dlg_grant_off_result_sub: "已在此设备上删除密钥 · 已在 {broker} 上吊销",
    dlg_grant_off_result_stale: "已在此设备上删除密钥 · {broker} 仍列出该设备，管理员可用 `kbmanage device revoke` 清除",
    dlg_grant_unsaved: "此设备无法更新自身的记录。",

    grant_confirm: "此设备无需浏览器登录即可访问你的网络驱动器，使用你在此设备上的账户。有效期：{days}。\r\n\r\n密钥保存在此设备的 TPM 中，无法复制出去。管理员可以随时吊销它。",
    dlg_grant_commit: "授权访问",
    dlg_grant_working: "正在授权此设备…",
    grant_done: "完成。此设备在 {days} 内无需浏览器登录。",

    notify_ready_title: "{realm} 访问已就绪",
    notify_ready_body: "{identity}。访问有效 {duration}。",
    notify_expiring_title: "{realm} 的访问将在 {duration} 后结束",
    notify_expiring_body: "续期未成功。{action}以保持访问。",
    notify_stopped_title: "{realm} 的访问已结束",
    notify_stopped_body: "{action}以重新获得访问。",
    notify_grant_due_title: "授权将在 {days} 后过期",
    notify_grant_due_body: "此设备无需浏览器登录即可访问 {realm}。请在 {date} 之前重新授权访问以保持这一能力。",

    settings_title: "NAS Access — 设置",
    tab_basic: "基本",
    tab_advanced: "高级",
    tab_about: "关于",
    settings_section_connection: "连接",
    settings_broker_label: "代理服务器 URL",
    settings_broker_sub: "要连接的服务器 — 由您的 IT 团队提供",
    settings_broker_managed: "由您的 IT 团队设置——此处无法更改。",
    settings_save: "保存",
    settings_gate: "配置完成后将显示授权和 Windows 配置",
    settings_section_signin: "登录",
    settings_startup_label: "登录时启动",
    settings_startup_sub: "在您登录后自动登录。",
    settings_startup_managed: "由您的 IT 团队为此计算机的所有用户开启。",
    settings_wam_label: "尽可能使用 Windows 登录",
    settings_wam_sub: "当 Windows 自带登录 (WAM) 无需询问即可完成时跳过浏览器。",
    settings_section_authorization: "授权",
    settings_grant_state: "已授权访问，身份为 {account}",
    settings_grant_for_label: "为以下账户授权此设备",
    settings_grant_for_sub: "留空表示你自己的账户，或填写此设备应作为其运行的另一个账户。",
    settings_section_windows: "Windows 配置",
    settings_enrolled: "Windows 已为 {realm} 配置。",
    settings_not_enrolled: "Windows 未为 {realm} 配置。",
    settings_section_troubleshoot: "疑难解答",
    settings_troubleshoot_sub: "本应用所做操作的详细技术记录，供他人帮助你排查问题时使用。",
    about_license: "自由软件：您可以按照 GNU 通用公共许可证（第 3 版或更高版本）重新分发和修改它。本程序不提供任何担保。",
    settings_ok: "确定",
    settings_cancel: "取消",
};
